// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/presentation/features/messages/messages_page_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:test_flutter_project/common/enums/server_failure.dart' as _i10;
import 'package:test_flutter_project/domain/entities/attachment_entity.dart'
    as _i7;
import 'package:test_flutter_project/domain/entities/conversation_entity.dart'
    as _i4;
import 'package:test_flutter_project/domain/entities/gif_entity.dart' as _i11;
import 'package:test_flutter_project/domain/entities/owner_entity.dart' as _i2;
import 'package:test_flutter_project/domain/entities/user_entity.dart' as _i15;
import 'package:test_flutter_project/domain/repositories/file_picker_repository.dart'
    as _i5;
import 'package:test_flutter_project/domain/repositories/owner_repository.dart'
    as _i8;
import 'package:test_flutter_project/domain/usecases/gifs/get_trending_gifs_use_case.dart'
    as _i12;
import 'package:test_flutter_project/domain/usecases/gifs/search_gifs_use_case.dart'
    as _i9;
import 'package:test_flutter_project/domain/usecases/inbox/extract_users_from_conversation_use_case.dart'
    as _i14;
import 'package:test_flutter_project/domain/usecases/inbox/get_conversation_by_id_use_case.dart'
    as _i13;
import 'package:test_flutter_project/utils/date_formatter.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOwnerEntity_0 extends _i1.SmartFake implements _i2.OwnerEntity {
  _FakeOwnerEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConversationEntity_2 extends _i1.SmartFake
    implements _i4.ConversationEntity {
  _FakeConversationEntity_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FilePickerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilePickerRepository extends _i1.Mock
    implements _i5.FilePickerRepository {
  @override
  _i6.Future<_i7.AttachmentEntity?> pickFile() => (super.noSuchMethod(
        Invocation.method(
          #pickFile,
          [],
        ),
        returnValue: _i6.Future<_i7.AttachmentEntity?>.value(),
        returnValueForMissingStub: _i6.Future<_i7.AttachmentEntity?>.value(),
      ) as _i6.Future<_i7.AttachmentEntity?>);
}

/// A class which mocks [OwnerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOwnerRepository extends _i1.Mock implements _i8.OwnerRepository {
  @override
  _i6.Future<List<_i2.OwnerEntity>> fetchOwners() => (super.noSuchMethod(
        Invocation.method(
          #fetchOwners,
          [],
        ),
        returnValue:
            _i6.Future<List<_i2.OwnerEntity>>.value(<_i2.OwnerEntity>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i2.OwnerEntity>>.value(<_i2.OwnerEntity>[]),
      ) as _i6.Future<List<_i2.OwnerEntity>>);

  @override
  _i2.OwnerEntity getOwnerById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getOwnerById,
          [id],
        ),
        returnValue: _FakeOwnerEntity_0(
          this,
          Invocation.method(
            #getOwnerById,
            [id],
          ),
        ),
        returnValueForMissingStub: _FakeOwnerEntity_0(
          this,
          Invocation.method(
            #getOwnerById,
            [id],
          ),
        ),
      ) as _i2.OwnerEntity);
}

/// A class which mocks [SearchGifsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchGifsUseCase extends _i1.Mock implements _i9.SearchGifsUseCase {
  @override
  _i6.Future<_i3.Either<_i10.ServerFailure, List<_i11.GifEntity>>> call(
          String? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i6
            .Future<_i3.Either<_i10.ServerFailure, List<_i11.GifEntity>>>.value(
            _FakeEither_1<_i10.ServerFailure, List<_i11.GifEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub: _i6
            .Future<_i3.Either<_i10.ServerFailure, List<_i11.GifEntity>>>.value(
            _FakeEither_1<_i10.ServerFailure, List<_i11.GifEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i10.ServerFailure, List<_i11.GifEntity>>>);
}

/// A class which mocks [GetTrendingGifsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTrendingGifsUseCase extends _i1.Mock
    implements _i12.GetTrendingGifsUseCase {
  @override
  _i6.Future<_i3.Either<_i10.ServerFailure, List<_i11.GifEntity>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6
            .Future<_i3.Either<_i10.ServerFailure, List<_i11.GifEntity>>>.value(
            _FakeEither_1<_i10.ServerFailure, List<_i11.GifEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub: _i6
            .Future<_i3.Either<_i10.ServerFailure, List<_i11.GifEntity>>>.value(
            _FakeEither_1<_i10.ServerFailure, List<_i11.GifEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i10.ServerFailure, List<_i11.GifEntity>>>);
}

/// A class which mocks [GetConversationByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetConversationByIdUseCase extends _i1.Mock
    implements _i13.GetConversationByIdUseCase {
  @override
  _i4.ConversationEntity call(String? params) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _FakeConversationEntity_2(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        ),
        returnValueForMissingStub: _FakeConversationEntity_2(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        ),
      ) as _i4.ConversationEntity);
}

/// A class which mocks [ExtractUsersFromConversationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockExtractUsersFromConversationUseCase extends _i1.Mock
    implements _i14.ExtractUsersFromConversationUseCase {
  @override
  Map<String, _i15.UserEntity?> call(_i4.ConversationEntity? conversation) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [conversation],
        ),
        returnValue: <String, _i15.UserEntity?>{},
        returnValueForMissingStub: <String, _i15.UserEntity?>{},
      ) as Map<String, _i15.UserEntity?>);
}

/// A class which mocks [DateFormatter].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateFormatter extends _i1.Mock implements _i16.DateFormatter {
  @override
  String formatMessageIncomingTime(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #formatMessageIncomingTime,
          [date],
        ),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.method(
            #formatMessageIncomingTime,
            [date],
          ),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.method(
            #formatMessageIncomingTime,
            [date],
          ),
        ),
      ) as String);

  @override
  String formatMessageDividerDate(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #formatMessageDividerDate,
          [date],
        ),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.method(
            #formatMessageDividerDate,
            [date],
          ),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.method(
            #formatMessageDividerDate,
            [date],
          ),
        ),
      ) as String);
}
