// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/presentation/features/messages/messages_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:test_flutter_project/domain/entities/attachment_entity.dart'
    as _i11;
import 'package:test_flutter_project/domain/entities/conversation_entity.dart'
    as _i4;
import 'package:test_flutter_project/domain/entities/owner_entity.dart' as _i5;
import 'package:test_flutter_project/domain/entities/user_entity.dart' as _i12;
import 'package:test_flutter_project/domain/models/message_model.dart' as _i8;
import 'package:test_flutter_project/presentation/features/inbox/inbox_page_cubit.dart'
    as _i6;
import 'package:test_flutter_project/presentation/features/inbox/inbox_page_state.dart'
    as _i2;
import 'package:test_flutter_project/presentation/features/messages/messages_page_cubit.dart'
    as _i10;
import 'package:test_flutter_project/presentation/features/messages/messages_page_state.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInboxPageState_0 extends _i1.SmartFake
    implements _i2.InboxPageState {
  _FakeInboxPageState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessagesPageState_1 extends _i1.SmartFake
    implements _i3.MessagesPageState {
  _FakeMessagesPageState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConversationEntity_2 extends _i1.SmartFake
    implements _i4.ConversationEntity {
  _FakeConversationEntity_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOwnerEntity_3 extends _i1.SmartFake implements _i5.OwnerEntity {
  _FakeOwnerEntity_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InboxPageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockInboxPageCubit extends _i1.Mock implements _i6.InboxPageCubit {
  @override
  _i2.InboxPageState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeInboxPageState_0(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeInboxPageState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.InboxPageState);

  @override
  _i7.Stream<_i2.InboxPageState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i7.Stream<_i2.InboxPageState>.empty(),
        returnValueForMissingStub: _i7.Stream<_i2.InboxPageState>.empty(),
      ) as _i7.Stream<_i2.InboxPageState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendMessage(
    String? conversationId,
    _i8.MessageModel? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            conversationId,
            message,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> markMessageAsRead(
    String? conversationId,
    int? messageIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMessageAsRead,
          [
            conversationId,
            messageIndex,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteConversation(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteConversation,
          [conversationId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  int getUnreadCountFromConversation(_i4.ConversationEntity? conversation) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnreadCountFromConversation,
          [conversation],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void emit(_i2.InboxPageState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i9.Change<_i2.InboxPageState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [MessagesPageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessagesPageCubit extends _i1.Mock implements _i10.MessagesPageCubit {
  @override
  int get activeRequestId => (super.noSuchMethod(
        Invocation.getter(#activeRequestId),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set activeRequestId(int? _activeRequestId) => super.noSuchMethod(
        Invocation.setter(
          #activeRequestId,
          _activeRequestId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.MessagesPageState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeMessagesPageState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeMessagesPageState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.MessagesPageState);

  @override
  _i7.Stream<_i3.MessagesPageState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i7.Stream<_i3.MessagesPageState>.empty(),
        returnValueForMissingStub: _i7.Stream<_i3.MessagesPageState>.empty(),
      ) as _i7.Stream<_i3.MessagesPageState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void setCurrentConversationId(String? conversationId) => super.noSuchMethod(
        Invocation.method(
          #setCurrentConversationId,
          [conversationId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> updateMessageText(String? newText) => (super.noSuchMethod(
        Invocation.method(
          #updateMessageText,
          [newText],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateGifsSearch(String? query) => (super.noSuchMethod(
        Invocation.method(
          #updateGifsSearch,
          [query],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void updateSelectedGif(String? newGifUrl) => super.noSuchMethod(
        Invocation.method(
          #updateSelectedGif,
          [newGifUrl],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i11.AttachmentEntity?> getAttachmentFile() => (super.noSuchMethod(
        Invocation.method(
          #getAttachmentFile,
          [],
        ),
        returnValue: _i7.Future<_i11.AttachmentEntity?>.value(),
        returnValueForMissingStub: _i7.Future<_i11.AttachmentEntity?>.value(),
      ) as _i7.Future<_i11.AttachmentEntity?>);

  @override
  _i4.ConversationEntity getConversationById(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversationById,
          [conversationId],
        ),
        returnValue: _FakeConversationEntity_2(
          this,
          Invocation.method(
            #getConversationById,
            [conversationId],
          ),
        ),
        returnValueForMissingStub: _FakeConversationEntity_2(
          this,
          Invocation.method(
            #getConversationById,
            [conversationId],
          ),
        ),
      ) as _i4.ConversationEntity);

  @override
  _i5.OwnerEntity getOwnerById(String? ownerId) => (super.noSuchMethod(
        Invocation.method(
          #getOwnerById,
          [ownerId],
        ),
        returnValue: _FakeOwnerEntity_3(
          this,
          Invocation.method(
            #getOwnerById,
            [ownerId],
          ),
        ),
        returnValueForMissingStub: _FakeOwnerEntity_3(
          this,
          Invocation.method(
            #getOwnerById,
            [ownerId],
          ),
        ),
      ) as _i5.OwnerEntity);

  @override
  Map<String, _i12.UserEntity?> getUsersFromConversation(
          _i4.ConversationEntity? conversation) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsersFromConversation,
          [conversation],
        ),
        returnValue: <String, _i12.UserEntity?>{},
        returnValueForMissingStub: <String, _i12.UserEntity?>{},
      ) as Map<String, _i12.UserEntity?>);

  @override
  String getMessageDividerDate(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #getMessageDividerDate,
          [date],
        ),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.method(
            #getMessageDividerDate,
            [date],
          ),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.method(
            #getMessageDividerDate,
            [date],
          ),
        ),
      ) as String);

  @override
  String getMessageTime(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #getMessageTime,
          [date],
        ),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.method(
            #getMessageTime,
            [date],
          ),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.method(
            #getMessageTime,
            [date],
          ),
        ),
      ) as String);

  @override
  void emit(_i3.MessagesPageState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i9.Change<_i3.MessagesPageState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
