// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/domain/usecases/gifs/get_trending_gifs_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:test_futter_project/common/enums/server_failure.dart' as _i5;
import 'package:test_futter_project/domain/entities/gif_entity.dart' as _i6;
import 'package:test_futter_project/domain/repositories/gifs_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [GifsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGifsRepository extends _i1.Mock implements _i3.GifsRepository {
  MockGifsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.GifEntity>>> searchGifs(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchGifs, [query]),
            returnValue: _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.GifEntity>>>.value(
              _FakeEither_0<_i5.ServerFailure, List<_i6.GifEntity>>(
                this,
                Invocation.method(#searchGifs, [query]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.GifEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.GifEntity>>> getTrending() =>
      (super.noSuchMethod(
            Invocation.method(#getTrending, []),
            returnValue: _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.GifEntity>>>.value(
              _FakeEither_0<_i5.ServerFailure, List<_i6.GifEntity>>(
                this,
                Invocation.method(#getTrending, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.ServerFailure, List<_i6.GifEntity>>>);
}
