// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/presentation/features/authentication/authentication_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_bloc/flutter_bloc.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:test_flutter_project/domain/entities/user_entity.dart' as _i7;
import 'package:test_flutter_project/domain/models/auth_result.dart' as _i5;
import 'package:test_flutter_project/domain/models/login_model.dart' as _i9;
import 'package:test_flutter_project/domain/models/register_model.dart' as _i11;
import 'package:test_flutter_project/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:test_flutter_project/domain/usecases/authentication/login_use_case.dart'
    as _i8;
import 'package:test_flutter_project/domain/usecases/authentication/register_use_case.dart'
    as _i10;
import 'package:test_flutter_project/presentation/features/user/user_data_cubit.dart'
    as _i12;
import 'package:test_flutter_project/presentation/features/user/user_data_state.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserDataState_0 extends _i1.SmartFake implements _i2.UserDataState {
  _FakeUserDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  @override
  _i4.Future<_i5.AuthResult> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue:
            _i4.Future<_i5.AuthResult>.value(_i6.dummyValue<_i5.AuthResult>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.AuthResult>.value(_i6.dummyValue<_i5.AuthResult>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i5.AuthResult>);

  @override
  _i4.Future<_i5.AuthResult> register({
    required String? email,
    required String? password,
    required String? firstName,
    required String? lastName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #email: email,
            #password: password,
            #firstName: firstName,
            #lastName: lastName,
          },
        ),
        returnValue:
            _i4.Future<_i5.AuthResult>.value(_i6.dummyValue<_i5.AuthResult>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.AuthResult>.value(_i6.dummyValue<_i5.AuthResult>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
            },
          ),
        )),
      ) as _i4.Future<_i5.AuthResult>);

  @override
  _i4.Future<void> logOut() => (super.noSuchMethod(
        Invocation.method(
          #logOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAccount(String? email) => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateUser(_i7.UserEntity? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isUserLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isUserLoggedIn,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i8.LoginUseCase {
  @override
  _i4.Future<_i5.AuthResult> call(_i9.LoginModel? model) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [model],
        ),
        returnValue:
            _i4.Future<_i5.AuthResult>.value(_i6.dummyValue<_i5.AuthResult>(
          this,
          Invocation.method(
            #call,
            [model],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.AuthResult>.value(_i6.dummyValue<_i5.AuthResult>(
          this,
          Invocation.method(
            #call,
            [model],
          ),
        )),
      ) as _i4.Future<_i5.AuthResult>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i10.RegisterUseCase {
  @override
  _i4.Future<_i5.AuthResult> call(_i11.RegisterModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [model],
        ),
        returnValue:
            _i4.Future<_i5.AuthResult>.value(_i6.dummyValue<_i5.AuthResult>(
          this,
          Invocation.method(
            #call,
            [model],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.AuthResult>.value(_i6.dummyValue<_i5.AuthResult>(
          this,
          Invocation.method(
            #call,
            [model],
          ),
        )),
      ) as _i4.Future<_i5.AuthResult>);
}

/// A class which mocks [UserDataCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataCubit extends _i1.Mock implements _i12.UserDataCubit {
  @override
  _i2.UserDataState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeUserDataState_0(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeUserDataState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.UserDataState);

  @override
  _i4.Stream<_i2.UserDataState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.UserDataState>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.UserDataState>.empty(),
      ) as _i4.Stream<_i2.UserDataState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isLocationPermissionGranted() => (super.noSuchMethod(
        Invocation.method(
          #isLocationPermissionGranted,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void setFirstName(String? firstName) => super.noSuchMethod(
        Invocation.method(
          #setFirstName,
          [firstName],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastName(String? lastName) => super.noSuchMethod(
        Invocation.method(
          #setLastName,
          [lastName],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setEmail(String? email) => super.noSuchMethod(
        Invocation.method(
          #setEmail,
          [email],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPassword(String? password) => super.noSuchMethod(
        Invocation.method(
          #setPassword,
          [password],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastSeenCar(String? carId) => super.noSuchMethod(
        Invocation.method(
          #setLastSeenCar,
          [carId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void checkLastSeenCarExpiration({required int? days}) => super.noSuchMethod(
        Invocation.method(
          #checkLastSeenCarExpiration,
          [],
          {#days: days},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> requestLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestLocationPermission,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> openLocationSettings() => (super.noSuchMethod(
        Invocation.method(
          #openLocationSettings,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void updateLocationPermissionStatus(bool? newStatus) => super.noSuchMethod(
        Invocation.method(
          #updateLocationPermissionStatus,
          [newStatus],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> updateAvatarImage() => (super.noSuchMethod(
        Invocation.method(
          #updateAvatarImage,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addCarIdToFavorites(String? carId) => super.noSuchMethod(
        Invocation.method(
          #addCarIdToFavorites,
          [carId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeCarIdFromFavorites(String? carId) => super.noSuchMethod(
        Invocation.method(
          #removeCarIdFromFavorites,
          [carId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addCarIdToCreated(String? carId) => super.noSuchMethod(
        Invocation.method(
          #addCarIdToCreated,
          [carId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeCarIdFromCreated(String? carId) => super.noSuchMethod(
        Invocation.method(
          #removeCarIdFromCreated,
          [carId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addCarToRecentlyViewed(String? carId) => super.noSuchMethod(
        Invocation.method(
          #addCarToRecentlyViewed,
          [carId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearFavorites() => super.noSuchMethod(
        Invocation.method(
          #clearFavorites,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearRecentItems() => super.noSuchMethod(
        Invocation.method(
          #clearRecentItems,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearMyItems() => super.noSuchMethod(
        Invocation.method(
          #clearMyItems,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAllData() => super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateRegion(String? region) => super.noSuchMethod(
        Invocation.method(
          #updateRegion,
          [region],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> authUser(String? email) => (super.noSuchMethod(
        Invocation.method(
          #authUser,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void logOutUser() => super.noSuchMethod(
        Invocation.method(
          #logOutUser,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateUser({
    required _i7.UserEntity? user,
    bool? updateCloud = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [],
          {
            #user: user,
            #updateCloud: updateCloud,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.UserDataState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i13.Change<_i2.UserDataState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
