# to update config, use $ pre-commit install
# to disable config, please use $ pre-commit uninstall

repos:
  # 1. Runs Dart Analysis (using your local Dart install)
  - repo: local
    hooks:
      - id: dart-analyze
        name: Dart Analyze
        entry: dart analyze --fatal-infos --fatal-warnings
        language: system
        files: \.dart$
        pass_filenames: false

  # 2. Fixes file formatting (adds newline at end, trims spaces)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        files: \.dart$
      - id: trailing-whitespace