repos:
  - repo: local
    hooks:
      - id: dart-analyze
        name: Dart Analyze
        description: Run dart analyze to check for errors.
        entry: dart analyze
        language: system
        files: \.dart$
        pass_filenames: false