targets:
  $default:
    builders:
      # Format is package_name|builder_name
      realm_generator|realm_generator:
        enabled: true
        generate_for:
          - apps/test_futter_project/lib/**
      freezed|freezed:
        enabled: true
        generate_for:
          - apps/test_futter_project/lib/**
      # Mockito's builder key is 'mockBuilder', not 'mockito'
      mockito|mockBuilder:
        enabled: true
        generate_for:
          - apps/test_futter_project/test/**
    sources:
      - apps/test_futter_project/lib/**
      - apps/test_futter_project/test/**
      - lib/** # Required: You must have a lib/ folder at root
      - $package$