name: test_futter_project
description: "Test Flutter Project for realm, go-router, rxDart and mockito"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  realm: ^20.2.0
  flutter_slidable: ^4.0.3
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  rxdart: ^0.28.0
  mockito: ^5.4.6
  bloc_test: ^10.0.0
  go_router: ^17.0.1
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  flutter_native_splash: ^2.4.7
  cached_network_image: ^3.4.1
  path_provider: ^2.0.15
  share_plus: ^12.0.1
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.2
  freezed: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mocks/
    - assets/images/
    - assets/images/country_flags/

  fonts:
    - family: Zona Pro
      fonts:
        - asset: assets/fonts/ZonaPro-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/ZonaPro-Light.otf
          weight: 400
        - asset: assets/fonts/ZonaPro-SemiBold.otf
          weight: 500
        - asset: assets/fonts/ZonaPro-Bold.otf
          weight: 700
