name: flutter_realm_test_workspace_root
publish_to: none

environment:
  sdk: '>=3.11.0 <4.0.0'

workspace:
  - apps/flutter_realm_test/

dev_dependencies:
  melos: ^7.0.0

melos:
  name: flutter_realm_test_workspace

  packages:
    - apps/**
    - packages/**

  scripts:
    hello: echo "Hello from Melos"
    test: flutter test .
    analyse: dart analyze .
    pods:clean:
      run: |
        melos exec --dir-exists="ios" -- \
          "cd ios && rm -rf Pods Podfile.lock && pod install"
      description: "Deep clean and reinstall iOS pods for all apps"
