// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/presentation/bloc/user/user_data_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:permission_handler/permission_handler.dart' as _i12;
import 'package:test_flutter_project/common/logger/base_logger.dart' as _i16;
import 'package:test_flutter_project/domain/data_sources/local/base_local_storage.dart'
    as _i7;
import 'package:test_flutter_project/domain/entities/car_entity.dart' as _i4;
import 'package:test_flutter_project/domain/entities/user_entity.dart' as _i3;
import 'package:test_flutter_project/domain/models/auth_result.dart' as _i2;
import 'package:test_flutter_project/domain/repositories/auth_repository.dart'
    as _i5;
import 'package:test_flutter_project/domain/usecases/database/delete_car_by_id_use_case.dart'
    as _i15;
import 'package:test_flutter_project/domain/usecases/geolocator/check_location_service_status_use_case.dart'
    as _i9;
import 'package:test_flutter_project/domain/usecases/geolocator/open_app_settings_use_case.dart'
    as _i8;
import 'package:test_flutter_project/domain/usecases/image_picker/pick_image_from_gallery_use_case.dart'
    as _i14;
import 'package:test_flutter_project/domain/usecases/permissions/check_location_permission_status_use_case.dart'
    as _i11;
import 'package:test_flutter_project/domain/usecases/permissions/request_location_permission_use_case.dart'
    as _i10;
import 'package:test_flutter_project/domain/usecases/users/get_user_by_email_use_case.dart'
    as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserEntity_1 extends _i1.SmartFake implements _i3.UserEntity {
  _FakeUserEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCarEntity_2 extends _i1.SmartFake implements _i4.CarEntity {
  _FakeCarEntity_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.AuthResult> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i2.AuthResult>);

  @override
  _i6.Future<_i2.AuthResult> register({
    required String? email,
    required String? password,
    required String? firstName,
    required String? lastName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #email: email,
            #password: password,
            #firstName: firstName,
            #lastName: lastName,
          },
        ),
        returnValue: _i6.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #register,
            [],
            {
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
            },
          ),
        )),
      ) as _i6.Future<_i2.AuthResult>);

  @override
  _i6.Future<void> logOut() => (super.noSuchMethod(
        Invocation.method(
          #logOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAccount(String? email) => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [email],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateUser(
    String? email,
    _i3.UserEntity? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [
            email,
            data,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isUserLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isUserLoggedIn,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [BaseLocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseLocalStorage extends _i1.Mock implements _i7.BaseLocalStorage {
  MockBaseLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.CarEntity> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <_i4.CarEntity>[],
      ) as List<_i4.CarEntity>);

  @override
  void add(dynamic T) => super.noSuchMethod(
        Invocation.method(
          #add,
          [T],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update(dynamic T) => super.noSuchMethod(
        Invocation.method(
          #update,
          [T],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Stream<dynamic> watch<T>() => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
        ),
        returnValue: _i6.Stream<dynamic>.empty(),
      ) as _i6.Stream<dynamic>);

  @override
  void deleteAllCars() => super.noSuchMethod(
        Invocation.method(
          #deleteAllCars,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteById(String? id) => super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.UserEntity initUser() => (super.noSuchMethod(
        Invocation.method(
          #initUser,
          [],
        ),
        returnValue: _FakeUserEntity_1(
          this,
          Invocation.method(
            #initUser,
            [],
          ),
        ),
      ) as _i3.UserEntity);

  @override
  _i4.CarEntity getCarById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getCarById,
          [id],
        ),
        returnValue: _FakeCarEntity_2(
          this,
          Invocation.method(
            #getCarById,
            [id],
          ),
        ),
      ) as _i4.CarEntity);

  @override
  int getMaxCarId() => (super.noSuchMethod(
        Invocation.method(
          #getMaxCarId,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  void clearUser() => super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OpenAppSettingsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenAppSettingsUseCase extends _i1.Mock
    implements _i8.OpenAppSettingsUseCase {
  MockOpenAppSettingsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [CheckLocationServiceStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckLocationServiceStatusUseCase extends _i1.Mock
    implements _i9.CheckLocationServiceStatusUseCase {
  MockCheckLocationServiceStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [RequestLocationPermissionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestLocationPermissionUseCase extends _i1.Mock
    implements _i10.RequestLocationPermissionUseCase {
  MockRequestLocationPermissionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [CheckLocationPermissionStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckLocationPermissionStatusUseCase extends _i1.Mock
    implements _i11.CheckLocationPermissionStatusUseCase {
  MockCheckLocationPermissionStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i12.PermissionStatus> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<_i12.PermissionStatus>.value(
            _i12.PermissionStatus.denied),
      ) as _i6.Future<_i12.PermissionStatus>);
}

/// A class which mocks [GetUserByEmailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserByEmailUseCase extends _i1.Mock
    implements _i13.GetUserByEmailUseCase {
  MockGetUserByEmailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UserEntity? call(String? params) => (super.noSuchMethod(Invocation.method(
        #call,
        [params],
      )) as _i3.UserEntity?);
}

/// A class which mocks [PickImageFromGalleryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPickImageFromGalleryUseCase extends _i1.Mock
    implements _i14.PickImageFromGalleryUseCase {
  MockPickImageFromGalleryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String?> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);
}

/// A class which mocks [DeleteCarByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteCarByIdUseCase extends _i1.Mock
    implements _i15.DeleteCarByIdUseCase {
  MockDeleteCarByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call(String? params) => super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BaseLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseLogger extends _i1.Mock implements _i16.BaseLogger {
  MockBaseLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void e(String? message) => super.noSuchMethod(
        Invocation.method(
          #e,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void i(String? message) => super.noSuchMethod(
        Invocation.method(
          #i,
          [message],
        ),
        returnValueForMissingStub: null,
      );
}
