// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/data/data_sources/remote/article_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:test_flutter_project/common/logger/base_logger.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BaseLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseLogger extends _i1.Mock implements _i2.BaseLogger {
  @override
  void e(String? message) =>
      super.noSuchMethod(Invocation.method(#e, [message]), returnValueForMissingStub: null);

  @override
  void i(String? message) =>
      super.noSuchMethod(Invocation.method(#i, [message]), returnValueForMissingStub: null);
}
