// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/presentation/bloc/article/article_page_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_futter_project/domain/entities/article_entity.dart' as _i2;
import 'package:test_futter_project/domain/usecases/articles/get_article_by_id_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeArticleEntity_0 extends _i1.SmartFake implements _i2.ArticleEntity {
  _FakeArticleEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetArticleByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetArticleByIdUseCase extends _i1.Mock
    implements _i3.GetArticleByIdUseCase {
  MockGetArticleByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ArticleEntity> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i4.Future<_i2.ArticleEntity>.value(
              _FakeArticleEntity_0(this, Invocation.method(#call, [id])),
            ),
          )
          as _i4.Future<_i2.ArticleEntity>);
}
