// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/presentation/bloc/user/user_data_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_futter_project/domain/data_sources/local/base_local_storage.dart'
    as _i4;
import 'package:test_futter_project/domain/entities/car_entity.dart' as _i3;
import 'package:test_futter_project/domain/entities/user_entity.dart' as _i2;
import 'package:test_futter_project/domain/usecases/geolocator/check_location_service_status_use_case.dart'
    as _i7;
import 'package:test_futter_project/domain/usecases/geolocator/open_app_settings_use_case.dart'
    as _i6;
import 'package:test_futter_project/domain/usecases/permissions/check_location_permission_status_use_case.dart'
    as _i9;
import 'package:test_futter_project/domain/usecases/permissions/request_location_permission_use_case.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCarEntity_1 extends _i1.SmartFake implements _i3.CarEntity {
  _FakeCarEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BaseLocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseLocalStorage extends _i1.Mock implements _i4.BaseLocalStorage {
  MockBaseLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.CarEntity> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: <_i3.CarEntity>[],
          )
          as List<_i3.CarEntity>);

  @override
  void add(dynamic T) => super.noSuchMethod(
    Invocation.method(#add, [T]),
    returnValueForMissingStub: null,
  );

  @override
  void update(dynamic T) => super.noSuchMethod(
    Invocation.method(#update, [T]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<dynamic> watch<T>() =>
      (super.noSuchMethod(
            Invocation.method(#watch, []),
            returnValue: _i5.Stream<dynamic>.empty(),
          )
          as _i5.Stream<dynamic>);

  @override
  void deleteAllCars() => super.noSuchMethod(
    Invocation.method(#deleteAllCars, []),
    returnValueForMissingStub: null,
  );

  @override
  void deleteById(String? id) => super.noSuchMethod(
    Invocation.method(#deleteById, [id]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.UserEntity initUser() =>
      (super.noSuchMethod(
            Invocation.method(#initUser, []),
            returnValue: _FakeUserEntity_0(
              this,
              Invocation.method(#initUser, []),
            ),
          )
          as _i2.UserEntity);

  @override
  _i3.CarEntity getCarById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCarById, [id]),
            returnValue: _FakeCarEntity_1(
              this,
              Invocation.method(#getCarById, [id]),
            ),
          )
          as _i3.CarEntity);

  @override
  int getMaxCarId() =>
      (super.noSuchMethod(Invocation.method(#getMaxCarId, []), returnValue: 0)
          as int);

  @override
  void clearUser() => super.noSuchMethod(
    Invocation.method(#clearUser, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OpenAppSettingsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenAppSettingsUseCase extends _i1.Mock
    implements _i6.OpenAppSettingsUseCase {
  MockOpenAppSettingsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [CheckLocationServiceStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckLocationServiceStatusUseCase extends _i1.Mock
    implements _i7.CheckLocationServiceStatusUseCase {
  MockCheckLocationServiceStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [RequestLocationPermissionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestLocationPermissionUseCase extends _i1.Mock
    implements _i8.RequestLocationPermissionUseCase {
  MockRequestLocationPermissionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [CheckLocationPermissionStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckLocationPermissionStatusUseCase extends _i1.Mock
    implements _i9.CheckLocationPermissionStatusUseCase {
  MockCheckLocationPermissionStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
