// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_flutter_project/domain/entities/owner_entity.dart' as _i4;
import 'package:test_flutter_project/domain/entities/user_entity.dart' as _i7;
import 'package:test_flutter_project/domain/usecases/owners/fetch_owners_use_case.dart' as _i2;
import 'package:test_flutter_project/domain/usecases/users/get_max_user_id_use_case.dart' as _i5;
import 'package:test_flutter_project/domain/usecases/users/save_users_use_case.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FetchOwnersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchOwnersUseCase extends _i1.Mock implements _i2.FetchOwnersUseCase {
  MockFetchOwnersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.OwnerEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<List<_i4.OwnerEntity>>.value(<_i4.OwnerEntity>[]),
          )
          as _i3.Future<List<_i4.OwnerEntity>>);
}

/// A class which mocks [GetMaxUserIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMaxUserIdUseCase extends _i1.Mock implements _i5.GetMaxUserIdUseCase {
  MockGetMaxUserIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int call() => (super.noSuchMethod(Invocation.method(#call, []), returnValue: 0) as int);
}

/// A class which mocks [SaveUsersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveUsersUseCase extends _i1.Mock implements _i6.SaveUsersUseCase {
  MockSaveUsersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(List<_i7.UserEntity>? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
