// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_flutter_project/domain/data_sources/remote/users_remote_data_source.dart'
    as _i5;
import 'package:test_flutter_project/domain/entities/owner_entity.dart' as _i2;
import 'package:test_flutter_project/domain/entities/user_entity.dart' as _i6;
import 'package:test_flutter_project/domain/repositories/owner_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOwnerEntity_0 extends _i1.SmartFake implements _i2.OwnerEntity {
  _FakeOwnerEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OwnerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOwnerRepository extends _i1.Mock implements _i3.OwnerRepository {
  @override
  _i4.Future<List<_i2.OwnerEntity>> fetchOwners() => (super.noSuchMethod(
        Invocation.method(
          #fetchOwners,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.OwnerEntity>>.value(<_i2.OwnerEntity>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.OwnerEntity>>.value(<_i2.OwnerEntity>[]),
      ) as _i4.Future<List<_i2.OwnerEntity>>);

  @override
  _i2.OwnerEntity getOwnerById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getOwnerById,
          [id],
        ),
        returnValue: _FakeOwnerEntity_0(
          this,
          Invocation.method(
            #getOwnerById,
            [id],
          ),
        ),
        returnValueForMissingStub: _FakeOwnerEntity_0(
          this,
          Invocation.method(
            #getOwnerById,
            [id],
          ),
        ),
      ) as _i2.OwnerEntity);
}

/// A class which mocks [UsersRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsersRemoteDataSource extends _i1.Mock
    implements _i5.UsersRemoteDataSource {
  @override
  List<_i6.UserEntity> get users => (super.noSuchMethod(
        Invocation.getter(#users),
        returnValue: <_i6.UserEntity>[],
        returnValueForMissingStub: <_i6.UserEntity>[],
      ) as List<_i6.UserEntity>);

  @override
  set users(List<_i6.UserEntity>? _users) => super.noSuchMethod(
        Invocation.setter(
          #users,
          _users,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> saveMockUsers(List<_i6.UserEntity>? users) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMockUsers,
          [users],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.UserEntity>> loadMockUsers() => (super.noSuchMethod(
        Invocation.method(
          #loadMockUsers,
          [],
        ),
        returnValue: _i4.Future<List<_i6.UserEntity>>.value(<_i6.UserEntity>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.UserEntity>>.value(<_i6.UserEntity>[]),
      ) as _i4.Future<List<_i6.UserEntity>>);

  @override
  _i6.UserEntity? getUserByEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #getUserByEmail,
          [email],
        ),
        returnValueForMissingStub: null,
      ) as _i6.UserEntity?);

  @override
  int getMaxUserId() => (super.noSuchMethod(
        Invocation.method(
          #getMaxUserId,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i6.UserEntity? getUserById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i6.UserEntity?);
}
