// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/data/repositories/auto_complete_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:test_futter_project/common/enums/car_type.dart' as _i5;
import 'package:test_futter_project/data/data_sources/remote/mock_auto_complete_remote_data_source_impl.dart'
    as _i2;
import 'package:test_futter_project/domain/entities/car_auto_complete_entity.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MockAutoCompleteRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockAutoCompleteRemoteDataSource extends _i1.Mock
    implements _i2.MockAutoCompleteRemoteDataSource {
  MockMockAutoCompleteRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CarAutoCompleteEntity>> getAutoCompleteModelListByType(
    _i5.CarType? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAutoCompleteModelListByType, [type]),
            returnValue: _i3.Future<List<_i4.CarAutoCompleteEntity>>.value(
              <_i4.CarAutoCompleteEntity>[],
            ),
          )
          as _i3.Future<List<_i4.CarAutoCompleteEntity>>);

  @override
  String getResourceByType(_i5.CarType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getResourceByType, [type]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getResourceByType, [type]),
            ),
          )
          as String);
}
