// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/data/repositories/car_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:realm/realm.dart' as _i9;
import 'package:test_flutter_project/common/enums/promo_type.dart' as _i11;
import 'package:test_flutter_project/data/data_sources/local/realm_local_storage.dart'
    as _i12;
import 'package:test_flutter_project/data/dto/car_dto.dart' as _i4;
import 'package:test_flutter_project/domain/data_sources/remote/car_remote_data_source.dart'
    as _i6;
import 'package:test_flutter_project/domain/entities/car_entity.dart' as _i3;
import 'package:test_flutter_project/domain/entities/engine_entity.dart' as _i2;
import 'package:test_flutter_project/domain/entities/owner_entity.dart' as _i10;
import 'package:test_flutter_project/domain/entities/user_entity.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEngineEntity_0 extends _i1.SmartFake implements _i2.EngineEntity {
  _FakeEngineEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCarEntity_1 extends _i1.SmartFake implements _i3.CarEntity {
  _FakeCarEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCarDto_2 extends _i1.SmartFake implements _i4.CarDto {
  _FakeCarDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserEntity_3 extends _i1.SmartFake implements _i5.UserEntity {
  _FakeUserEntity_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CarRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarRemoteDataSource extends _i1.Mock
    implements _i6.CarRemoteDataSource {
  @override
  _i7.Stream<List<_i4.CarDto>> get carStream => (super.noSuchMethod(
        Invocation.getter(#carStream),
        returnValue: _i7.Stream<List<_i4.CarDto>>.empty(),
        returnValueForMissingStub: _i7.Stream<List<_i4.CarDto>>.empty(),
      ) as _i7.Stream<List<_i4.CarDto>>);

  @override
  _i7.Future<List<_i4.CarDto>> fetchCars() => (super.noSuchMethod(
        Invocation.method(
          #fetchCars,
          [],
        ),
        returnValue: _i7.Future<List<_i4.CarDto>>.value(<_i4.CarDto>[]),
        returnValueForMissingStub:
            _i7.Future<List<_i4.CarDto>>.value(<_i4.CarDto>[]),
      ) as _i7.Future<List<_i4.CarDto>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CarEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarEntity extends _i1.Mock implements _i3.CarEntity {
  @override
  String get carId => (super.noSuchMethod(
        Invocation.getter(#carId),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#carId),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#carId),
        ),
      ) as String);

  @override
  String get model => (super.noSuchMethod(
        Invocation.getter(#model),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#model),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#model),
        ),
      ) as String);

  @override
  String get manufacturer => (super.noSuchMethod(
        Invocation.getter(#manufacturer),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#manufacturer),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#manufacturer),
        ),
      ) as String);

  @override
  String get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
      ) as String);

  @override
  String get bodyType => (super.noSuchMethod(
        Invocation.getter(#bodyType),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#bodyType),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#bodyType),
        ),
      ) as String);

  @override
  _i2.EngineEntity get engine => (super.noSuchMethod(
        Invocation.getter(#engine),
        returnValue: _FakeEngineEntity_0(
          this,
          Invocation.getter(#engine),
        ),
        returnValueForMissingStub: _FakeEngineEntity_0(
          this,
          Invocation.getter(#engine),
        ),
      ) as _i2.EngineEntity);

  @override
  String get transmissionType => (super.noSuchMethod(
        Invocation.getter(#transmissionType),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#transmissionType),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#transmissionType),
        ),
      ) as String);

  @override
  bool get isVerified => (super.noSuchMethod(
        Invocation.getter(#isVerified),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<String> get images => (super.noSuchMethod(
        Invocation.getter(#images),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  bool get isShown => (super.noSuchMethod(
        Invocation.getter(#isShown),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.CarEntity copyWith({
    _i9.ObjectId? id,
    String? carId,
    String? model,
    String? manufacturer,
    String? type,
    String? year,
    String? color,
    _i10.OwnerEntity? owner,
    String? bodyType,
    _i2.EngineEntity? engine,
    String? transmissionType,
    bool? isVerified,
    _i11.PromoType? promoType,
    int? mileage,
    int? distanceTo,
    int? price,
    List<String>? images,
    bool? isShown,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #id: id,
            #carId: carId,
            #model: model,
            #manufacturer: manufacturer,
            #type: type,
            #year: year,
            #color: color,
            #owner: owner,
            #bodyType: bodyType,
            #engine: engine,
            #transmissionType: transmissionType,
            #isVerified: isVerified,
            #promoType: promoType,
            #mileage: mileage,
            #distanceTo: distanceTo,
            #price: price,
            #images: images,
            #isShown: isShown,
          },
        ),
        returnValue: _FakeCarEntity_1(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #carId: carId,
              #model: model,
              #manufacturer: manufacturer,
              #type: type,
              #year: year,
              #color: color,
              #owner: owner,
              #bodyType: bodyType,
              #engine: engine,
              #transmissionType: transmissionType,
              #isVerified: isVerified,
              #promoType: promoType,
              #mileage: mileage,
              #distanceTo: distanceTo,
              #price: price,
              #images: images,
              #isShown: isShown,
            },
          ),
        ),
        returnValueForMissingStub: _FakeCarEntity_1(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #carId: carId,
              #model: model,
              #manufacturer: manufacturer,
              #type: type,
              #year: year,
              #color: color,
              #owner: owner,
              #bodyType: bodyType,
              #engine: engine,
              #transmissionType: transmissionType,
              #isVerified: isVerified,
              #promoType: promoType,
              #mileage: mileage,
              #distanceTo: distanceTo,
              #price: price,
              #images: images,
              #isShown: isShown,
            },
          ),
        ),
      ) as _i3.CarEntity);
}

/// A class which mocks [CarDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarDto extends _i1.Mock implements _i4.CarDto {
  @override
  String get carId => (super.noSuchMethod(
        Invocation.getter(#carId),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#carId),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#carId),
        ),
      ) as String);

  @override
  String get model => (super.noSuchMethod(
        Invocation.getter(#model),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#model),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#model),
        ),
      ) as String);

  @override
  String get manufacturer => (super.noSuchMethod(
        Invocation.getter(#manufacturer),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#manufacturer),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#manufacturer),
        ),
      ) as String);

  @override
  String get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
      ) as String);

  @override
  String get bodyType => (super.noSuchMethod(
        Invocation.getter(#bodyType),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#bodyType),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#bodyType),
        ),
      ) as String);

  @override
  _i2.EngineEntity get engine => (super.noSuchMethod(
        Invocation.getter(#engine),
        returnValue: _FakeEngineEntity_0(
          this,
          Invocation.getter(#engine),
        ),
        returnValueForMissingStub: _FakeEngineEntity_0(
          this,
          Invocation.getter(#engine),
        ),
      ) as _i2.EngineEntity);

  @override
  String get transmissionType => (super.noSuchMethod(
        Invocation.getter(#transmissionType),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#transmissionType),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#transmissionType),
        ),
      ) as String);

  @override
  bool get isVerified => (super.noSuchMethod(
        Invocation.getter(#isVerified),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<String> get images => (super.noSuchMethod(
        Invocation.getter(#images),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  _i4.CarDto copyWith({
    _i9.ObjectId? id,
    String? carId,
    String? model,
    String? manufacturer,
    String? type,
    String? year,
    String? color,
    String? bodyType,
    _i2.EngineEntity? engine,
    String? transmissionType,
    _i10.OwnerEntity? owner,
    bool? isVerified,
    _i11.PromoType? promoType,
    int? mileage,
    int? distanceTo,
    int? price,
    List<String>? images,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #id: id,
            #carId: carId,
            #model: model,
            #manufacturer: manufacturer,
            #type: type,
            #year: year,
            #color: color,
            #bodyType: bodyType,
            #engine: engine,
            #transmissionType: transmissionType,
            #owner: owner,
            #isVerified: isVerified,
            #promoType: promoType,
            #mileage: mileage,
            #distanceTo: distanceTo,
            #price: price,
            #images: images,
          },
        ),
        returnValue: _FakeCarDto_2(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #carId: carId,
              #model: model,
              #manufacturer: manufacturer,
              #type: type,
              #year: year,
              #color: color,
              #bodyType: bodyType,
              #engine: engine,
              #transmissionType: transmissionType,
              #owner: owner,
              #isVerified: isVerified,
              #promoType: promoType,
              #mileage: mileage,
              #distanceTo: distanceTo,
              #price: price,
              #images: images,
            },
          ),
        ),
        returnValueForMissingStub: _FakeCarDto_2(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #carId: carId,
              #model: model,
              #manufacturer: manufacturer,
              #type: type,
              #year: year,
              #color: color,
              #bodyType: bodyType,
              #engine: engine,
              #transmissionType: transmissionType,
              #owner: owner,
              #isVerified: isVerified,
              #promoType: promoType,
              #mileage: mileage,
              #distanceTo: distanceTo,
              #price: price,
              #images: images,
            },
          ),
        ),
      ) as _i4.CarDto);
}

/// A class which mocks [RealmLocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealmLocalStorage extends _i1.Mock implements _i12.RealmLocalStorage {
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void addCar(_i3.CarEntity? car) => super.noSuchMethod(
        Invocation.method(
          #addCar,
          [car],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateCar(_i3.CarEntity? car) => super.noSuchMethod(
        Invocation.method(
          #updateCar,
          [car],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Stream<dynamic> watchCars() => (super.noSuchMethod(
        Invocation.method(
          #watchCars,
          [],
        ),
        returnValue: _i7.Stream<dynamic>.empty(),
        returnValueForMissingStub: _i7.Stream<dynamic>.empty(),
      ) as _i7.Stream<dynamic>);

  @override
  List<_i3.CarEntity> getAllCars() => (super.noSuchMethod(
        Invocation.method(
          #getAllCars,
          [],
        ),
        returnValue: <_i3.CarEntity>[],
        returnValueForMissingStub: <_i3.CarEntity>[],
      ) as List<_i3.CarEntity>);

  @override
  void deleteCarById(String? id) => super.noSuchMethod(
        Invocation.method(
          #deleteCarById,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteAllCars() => super.noSuchMethod(
        Invocation.method(
          #deleteAllCars,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.CarEntity? getCarById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getCarById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i3.CarEntity?);

  @override
  int getMaxCarId() => (super.noSuchMethod(
        Invocation.method(
          #getMaxCarId,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i5.UserEntity initUser() => (super.noSuchMethod(
        Invocation.method(
          #initUser,
          [],
        ),
        returnValue: _FakeUserEntity_3(
          this,
          Invocation.method(
            #initUser,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeUserEntity_3(
          this,
          Invocation.method(
            #initUser,
            [],
          ),
        ),
      ) as _i5.UserEntity);

  @override
  void updateUser(_i5.UserEntity? user) => super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearUser() => super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
