// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/data/repositories/car_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:realm/realm.dart' as _i5;
import 'package:test_flutter_project/common/enums/promo_type.dart' as _i11;
import 'package:test_flutter_project/data/data_sources/local/realm_local_storage.dart'
    as _i12;
import 'package:test_flutter_project/data/dto/car_dto.dart' as _i4;
import 'package:test_flutter_project/domain/data_sources/remote/car_remote_data_source.dart'
    as _i7;
import 'package:test_flutter_project/domain/entities/car_entity.dart' as _i3;
import 'package:test_flutter_project/domain/entities/engine_entity.dart' as _i2;
import 'package:test_flutter_project/domain/entities/owner_entity.dart' as _i10;
import 'package:test_flutter_project/domain/entities/user_entity.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEngineEntity_0 extends _i1.SmartFake implements _i2.EngineEntity {
  _FakeEngineEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCarEntity_1 extends _i1.SmartFake implements _i3.CarEntity {
  _FakeCarEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCarDto_2 extends _i1.SmartFake implements _i4.CarDto {
  _FakeCarDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealm_3 extends _i1.SmartFake implements _i5.Realm {
  _FakeRealm_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserEntity_4 extends _i1.SmartFake implements _i6.UserEntity {
  _FakeUserEntity_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CarRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarRemoteDataSource extends _i1.Mock
    implements _i7.CarRemoteDataSource {
  @override
  _i8.Stream<List<_i4.CarDto>> get carStream => (super.noSuchMethod(
        Invocation.getter(#carStream),
        returnValue: _i8.Stream<List<_i4.CarDto>>.empty(),
        returnValueForMissingStub: _i8.Stream<List<_i4.CarDto>>.empty(),
      ) as _i8.Stream<List<_i4.CarDto>>);

  @override
  _i8.Future<List<_i4.CarDto>> fetchCars() => (super.noSuchMethod(
        Invocation.method(
          #fetchCars,
          [],
        ),
        returnValue: _i8.Future<List<_i4.CarDto>>.value(<_i4.CarDto>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i4.CarDto>>.value(<_i4.CarDto>[]),
      ) as _i8.Future<List<_i4.CarDto>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CarEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarEntity extends _i1.Mock implements _i3.CarEntity {
  @override
  String get carId => (super.noSuchMethod(
        Invocation.getter(#carId),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#carId),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#carId),
        ),
      ) as String);

  @override
  String get model => (super.noSuchMethod(
        Invocation.getter(#model),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#model),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#model),
        ),
      ) as String);

  @override
  String get manufacturer => (super.noSuchMethod(
        Invocation.getter(#manufacturer),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#manufacturer),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#manufacturer),
        ),
      ) as String);

  @override
  String get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
      ) as String);

  @override
  String get bodyType => (super.noSuchMethod(
        Invocation.getter(#bodyType),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#bodyType),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#bodyType),
        ),
      ) as String);

  @override
  _i2.EngineEntity get engine => (super.noSuchMethod(
        Invocation.getter(#engine),
        returnValue: _FakeEngineEntity_0(
          this,
          Invocation.getter(#engine),
        ),
        returnValueForMissingStub: _FakeEngineEntity_0(
          this,
          Invocation.getter(#engine),
        ),
      ) as _i2.EngineEntity);

  @override
  String get transmissionType => (super.noSuchMethod(
        Invocation.getter(#transmissionType),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#transmissionType),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#transmissionType),
        ),
      ) as String);

  @override
  bool get isVerified => (super.noSuchMethod(
        Invocation.getter(#isVerified),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<String> get images => (super.noSuchMethod(
        Invocation.getter(#images),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  bool get isShown => (super.noSuchMethod(
        Invocation.getter(#isShown),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.CarEntity copyWith({
    dynamic id,
    String? carId,
    String? model,
    String? manufacturer,
    String? type,
    String? year,
    String? color,
    _i10.OwnerEntity? owner,
    String? bodyType,
    _i2.EngineEntity? engine,
    String? transmissionType,
    bool? isVerified,
    _i11.PromoType? promoType,
    int? mileage,
    int? distanceTo,
    int? price,
    List<String>? images,
    bool? isShown,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #id: id,
            #carId: carId,
            #model: model,
            #manufacturer: manufacturer,
            #type: type,
            #year: year,
            #color: color,
            #owner: owner,
            #bodyType: bodyType,
            #engine: engine,
            #transmissionType: transmissionType,
            #isVerified: isVerified,
            #promoType: promoType,
            #mileage: mileage,
            #distanceTo: distanceTo,
            #price: price,
            #images: images,
            #isShown: isShown,
          },
        ),
        returnValue: _FakeCarEntity_1(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #carId: carId,
              #model: model,
              #manufacturer: manufacturer,
              #type: type,
              #year: year,
              #color: color,
              #owner: owner,
              #bodyType: bodyType,
              #engine: engine,
              #transmissionType: transmissionType,
              #isVerified: isVerified,
              #promoType: promoType,
              #mileage: mileage,
              #distanceTo: distanceTo,
              #price: price,
              #images: images,
              #isShown: isShown,
            },
          ),
        ),
        returnValueForMissingStub: _FakeCarEntity_1(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #carId: carId,
              #model: model,
              #manufacturer: manufacturer,
              #type: type,
              #year: year,
              #color: color,
              #owner: owner,
              #bodyType: bodyType,
              #engine: engine,
              #transmissionType: transmissionType,
              #isVerified: isVerified,
              #promoType: promoType,
              #mileage: mileage,
              #distanceTo: distanceTo,
              #price: price,
              #images: images,
              #isShown: isShown,
            },
          ),
        ),
      ) as _i3.CarEntity);
}

/// A class which mocks [CarDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarDto extends _i1.Mock implements _i4.CarDto {
  @override
  String get carId => (super.noSuchMethod(
        Invocation.getter(#carId),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#carId),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#carId),
        ),
      ) as String);

  @override
  String get model => (super.noSuchMethod(
        Invocation.getter(#model),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#model),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#model),
        ),
      ) as String);

  @override
  String get manufacturer => (super.noSuchMethod(
        Invocation.getter(#manufacturer),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#manufacturer),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#manufacturer),
        ),
      ) as String);

  @override
  String get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
      ) as String);

  @override
  String get bodyType => (super.noSuchMethod(
        Invocation.getter(#bodyType),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#bodyType),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#bodyType),
        ),
      ) as String);

  @override
  _i2.EngineEntity get engine => (super.noSuchMethod(
        Invocation.getter(#engine),
        returnValue: _FakeEngineEntity_0(
          this,
          Invocation.getter(#engine),
        ),
        returnValueForMissingStub: _FakeEngineEntity_0(
          this,
          Invocation.getter(#engine),
        ),
      ) as _i2.EngineEntity);

  @override
  String get transmissionType => (super.noSuchMethod(
        Invocation.getter(#transmissionType),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#transmissionType),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#transmissionType),
        ),
      ) as String);

  @override
  bool get isVerified => (super.noSuchMethod(
        Invocation.getter(#isVerified),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set mileage(int? _mileage) => super.noSuchMethod(
        Invocation.setter(
          #mileage,
          _mileage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set distanceTo(int? _distanceTo) => super.noSuchMethod(
        Invocation.setter(
          #distanceTo,
          _distanceTo,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set price(int? _price) => super.noSuchMethod(
        Invocation.setter(
          #price,
          _price,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> get images => (super.noSuchMethod(
        Invocation.getter(#images),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  set images(List<String>? _images) => super.noSuchMethod(
        Invocation.setter(
          #images,
          _images,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.CarDto copyWith({
    dynamic id,
    String? carId,
    String? model,
    String? manufacturer,
    String? type,
    String? year,
    String? color,
    String? bodyType,
    _i2.EngineEntity? engine,
    String? transmissionType,
    _i10.OwnerEntity? owner,
    bool? isVerified,
    _i11.PromoType? promoType,
    int? mileage,
    int? distanceTo,
    int? price,
    List<String>? images,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #id: id,
            #carId: carId,
            #model: model,
            #manufacturer: manufacturer,
            #type: type,
            #year: year,
            #color: color,
            #bodyType: bodyType,
            #engine: engine,
            #transmissionType: transmissionType,
            #owner: owner,
            #isVerified: isVerified,
            #promoType: promoType,
            #mileage: mileage,
            #distanceTo: distanceTo,
            #price: price,
            #images: images,
          },
        ),
        returnValue: _FakeCarDto_2(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #carId: carId,
              #model: model,
              #manufacturer: manufacturer,
              #type: type,
              #year: year,
              #color: color,
              #bodyType: bodyType,
              #engine: engine,
              #transmissionType: transmissionType,
              #owner: owner,
              #isVerified: isVerified,
              #promoType: promoType,
              #mileage: mileage,
              #distanceTo: distanceTo,
              #price: price,
              #images: images,
            },
          ),
        ),
        returnValueForMissingStub: _FakeCarDto_2(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #id: id,
              #carId: carId,
              #model: model,
              #manufacturer: manufacturer,
              #type: type,
              #year: year,
              #color: color,
              #bodyType: bodyType,
              #engine: engine,
              #transmissionType: transmissionType,
              #owner: owner,
              #isVerified: isVerified,
              #promoType: promoType,
              #mileage: mileage,
              #distanceTo: distanceTo,
              #price: price,
              #images: images,
            },
          ),
        ),
      ) as _i4.CarDto);
}

/// A class which mocks [RealmLocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealmLocalStorage extends _i1.Mock implements _i12.RealmLocalStorage {
  @override
  _i5.Realm get realm => (super.noSuchMethod(
        Invocation.getter(#realm),
        returnValue: _FakeRealm_3(
          this,
          Invocation.getter(#realm),
        ),
        returnValueForMissingStub: _FakeRealm_3(
          this,
          Invocation.getter(#realm),
        ),
      ) as _i5.Realm);

  @override
  void add(dynamic T) => super.noSuchMethod(
        Invocation.method(
          #add,
          [T],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update(dynamic T) => super.noSuchMethod(
        Invocation.method(
          #update,
          [T],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Stream<dynamic> watch<T>() => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
        ),
        returnValue: _i8.Stream<dynamic>.empty(),
        returnValueForMissingStub: _i8.Stream<dynamic>.empty(),
      ) as _i8.Stream<dynamic>);

  @override
  List<_i3.CarEntity> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: <_i3.CarEntity>[],
        returnValueForMissingStub: <_i3.CarEntity>[],
      ) as List<_i3.CarEntity>);

  @override
  void deleteById(String? id) => super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteAllCars() => super.noSuchMethod(
        Invocation.method(
          #deleteAllCars,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.UserEntity initUser() => (super.noSuchMethod(
        Invocation.method(
          #initUser,
          [],
        ),
        returnValue: _FakeUserEntity_4(
          this,
          Invocation.method(
            #initUser,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeUserEntity_4(
          this,
          Invocation.method(
            #initUser,
            [],
          ),
        ),
      ) as _i6.UserEntity);

  @override
  _i3.CarEntity getCarById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getCarById,
          [id],
        ),
        returnValue: _FakeCarEntity_1(
          this,
          Invocation.method(
            #getCarById,
            [id],
          ),
        ),
        returnValueForMissingStub: _FakeCarEntity_1(
          this,
          Invocation.method(
            #getCarById,
            [id],
          ),
        ),
      ) as _i3.CarEntity);

  @override
  int getMaxCarId() => (super.noSuchMethod(
        Invocation.method(
          #getMaxCarId,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void clearUser() => super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
