// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/data/repositories/permission_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:permission_handler/permission_handler.dart' as _i4;
import 'package:test_flutter_project/domain/data_sources/local/permission_local_data_source.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PermissionLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionLocalDataSource extends _i1.Mock implements _i2.PermissionLocalDataSource {
  MockPermissionLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.PermissionStatus> requestLocation() =>
      (super.noSuchMethod(
            Invocation.method(#requestLocation, []),
            returnValue: _i3.Future<_i4.PermissionStatus>.value(_i4.PermissionStatus.denied),
          )
          as _i3.Future<_i4.PermissionStatus>);

  @override
  _i3.Future<_i4.PermissionStatus> checkLocationStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkLocationStatus, []),
            returnValue: _i3.Future<_i4.PermissionStatus>.value(_i4.PermissionStatus.denied),
          )
          as _i3.Future<_i4.PermissionStatus>);
}
