// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/presentation/bloc/home/explore_page_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_flutter_project/domain/entities/article_entity.dart' as _i6;
import 'package:test_flutter_project/domain/usecases/articles/fetch_articles_use_case.dart' as _i5;
import 'package:test_flutter_project/domain/usecases/database/sync_cars_use_case.dart' as _i2;
import 'package:test_flutter_project/domain/usecases/database/watch_cars_use_case.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SyncCarsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncCarsUseCase extends _i1.Mock implements _i2.SyncCarsUseCase {
  MockSyncCarsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [WatchCarsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchCarsUseCase extends _i1.Mock implements _i4.WatchCarsUseCase {
  MockWatchCarsUseCase() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [FetchArticlesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchArticlesUseCase extends _i1.Mock implements _i5.FetchArticlesUseCase {
  MockFetchArticlesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.ArticleEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<List<_i6.ArticleEntity>>.value(<_i6.ArticleEntity>[]),
          )
          as _i3.Future<List<_i6.ArticleEntity>>);
}
