// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/data/data_sources/local/file_picker_local_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:cross_file/cross_file.dart' as _i5;
import 'package:file_picker/file_picker.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FilePickerIO].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilePickerIO extends _i1.Mock implements _i2.FilePickerIO {
  MockFilePickerIO() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.FilePickerResult?> pickFiles({
    _i2.FileType? type = _i2.FileType.any,
    List<String>? allowedExtensions,
    String? dialogTitle,
    String? initialDirectory,
    dynamic Function(_i2.FilePickerStatus)? onFileLoading,
    bool? allowCompression = false,
    bool? allowMultiple = false,
    bool? withData = false,
    int? compressionQuality = 0,
    bool? withReadStream = false,
    bool? lockParentWindow = false,
    bool? readSequential = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickFiles, [], {
              #type: type,
              #allowedExtensions: allowedExtensions,
              #dialogTitle: dialogTitle,
              #initialDirectory: initialDirectory,
              #onFileLoading: onFileLoading,
              #allowCompression: allowCompression,
              #allowMultiple: allowMultiple,
              #withData: withData,
              #compressionQuality: compressionQuality,
              #withReadStream: withReadStream,
              #lockParentWindow: lockParentWindow,
              #readSequential: readSequential,
            }),
            returnValue: _i3.Future<_i2.FilePickerResult?>.value(),
          )
          as _i3.Future<_i2.FilePickerResult?>);

  @override
  _i3.Future<bool?> clearTemporaryFiles() =>
      (super.noSuchMethod(
            Invocation.method(#clearTemporaryFiles, []),
            returnValue: _i3.Future<bool?>.value(),
          )
          as _i3.Future<bool?>);

  @override
  _i3.Future<String?> getDirectoryPath({
    String? dialogTitle,
    bool? lockParentWindow = false,
    String? initialDirectory,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDirectoryPath, [], {
              #dialogTitle: dialogTitle,
              #lockParentWindow: lockParentWindow,
              #initialDirectory: initialDirectory,
            }),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> saveFile({
    String? dialogTitle,
    String? fileName,
    String? initialDirectory,
    _i2.FileType? type = _i2.FileType.any,
    List<String>? allowedExtensions,
    _i4.Uint8List? bytes,
    bool? lockParentWindow = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveFile, [], {
              #dialogTitle: dialogTitle,
              #fileName: fileName,
              #initialDirectory: initialDirectory,
              #type: type,
              #allowedExtensions: allowedExtensions,
              #bytes: bytes,
              #lockParentWindow: lockParentWindow,
            }),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<List<String>?> pickFileAndDirectoryPaths({
    String? initialDirectory,
    _i2.FileType? type = _i2.FileType.any,
    List<String>? allowedExtensions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickFileAndDirectoryPaths, [], {
              #initialDirectory: initialDirectory,
              #type: type,
              #allowedExtensions: allowedExtensions,
            }),
            returnValue: _i3.Future<List<String>?>.value(),
          )
          as _i3.Future<List<String>?>);
}

/// A class which mocks [FilePickerResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilePickerResult extends _i1.Mock implements _i2.FilePickerResult {
  MockFilePickerResult() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.PlatformFile> get files =>
      (super.noSuchMethod(Invocation.getter(#files), returnValue: <_i2.PlatformFile>[])
          as List<_i2.PlatformFile>);

  @override
  bool get isSinglePick =>
      (super.noSuchMethod(Invocation.getter(#isSinglePick), returnValue: false) as bool);

  @override
  int get count => (super.noSuchMethod(Invocation.getter(#count), returnValue: 0) as int);

  @override
  List<String?> get paths =>
      (super.noSuchMethod(Invocation.getter(#paths), returnValue: <String?>[]) as List<String?>);

  @override
  List<String?> get names =>
      (super.noSuchMethod(Invocation.getter(#names), returnValue: <String?>[]) as List<String?>);

  @override
  List<_i5.XFile> get xFiles =>
      (super.noSuchMethod(Invocation.getter(#xFiles), returnValue: <_i5.XFile>[])
          as List<_i5.XFile>);
}
