// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/presentation/pages/messages/messages_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:flutter/cupertino.dart' as _i14;
import 'package:flutter_bloc/flutter_bloc.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:test_flutter_project/domain/entities/attachment_entity.dart' as _i17;
import 'package:test_flutter_project/domain/entities/owner_entity.dart' as _i3;
import 'package:test_flutter_project/domain/entities/user_entity.dart' as _i9;
import 'package:test_flutter_project/domain/models/conversation_model.dart' as _i2;
import 'package:test_flutter_project/domain/models/message_model.dart' as _i13;
import 'package:test_flutter_project/domain/usecases/inbox/extract_users_from_conversation_use_case.dart'
    as _i8;
import 'package:test_flutter_project/domain/usecases/inbox/get_conversation_by_id_use_case.dart'
    as _i6;
import 'package:test_flutter_project/domain/usecases/owners/get_owner_by_id_use_case.dart' as _i7;
import 'package:test_flutter_project/domain/usecases/users/get_user_by_id_use_case.dart' as _i10;
import 'package:test_flutter_project/presentation/bloc/home/inbox_page/inbox_page_cubit.dart'
    as _i11;
import 'package:test_flutter_project/presentation/bloc/home/inbox_page/inbox_page_state.dart'
    as _i4;
import 'package:test_flutter_project/presentation/bloc/messages/messages_page_cubit.dart' as _i16;
import 'package:test_flutter_project/presentation/bloc/messages/messages_page_state.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConversationModel_0 extends _i1.SmartFake implements _i2.ConversationModel {
  _FakeConversationModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOwnerEntity_1 extends _i1.SmartFake implements _i3.OwnerEntity {
  _FakeOwnerEntity_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeInboxPageState_2 extends _i1.SmartFake implements _i4.InboxPageState {
  _FakeInboxPageState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessagesPageState_3 extends _i1.SmartFake implements _i5.MessagesPageState {
  _FakeMessagesPageState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetConversationByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetConversationByIdUseCase extends _i1.Mock implements _i6.GetConversationByIdUseCase {
  MockGetConversationByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ConversationModel call(String? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _FakeConversationModel_0(this, Invocation.method(#call, [params])),
          )
          as _i2.ConversationModel);
}

/// A class which mocks [GetOwnerByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOwnerByIdUseCase extends _i1.Mock implements _i7.GetOwnerByIdUseCase {
  MockGetOwnerByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.OwnerEntity call(String? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _FakeOwnerEntity_1(this, Invocation.method(#call, [params])),
          )
          as _i3.OwnerEntity);
}

/// A class which mocks [ExtractUsersFromConversationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockExtractUsersFromConversationUseCase extends _i1.Mock
    implements _i8.ExtractUsersFromConversationUseCase {
  MockExtractUsersFromConversationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i9.UserEntity?> call(_i2.ConversationModel? conversation) =>
      (super.noSuchMethod(
            Invocation.method(#call, [conversation]),
            returnValue: <String, _i9.UserEntity?>{},
          )
          as Map<String, _i9.UserEntity?>);
}

/// A class which mocks [GetUserByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserByIdUseCase extends _i1.Mock implements _i10.GetUserByIdUseCase {
  MockGetUserByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.UserEntity? call(String? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params])) as _i9.UserEntity?);
}

/// A class which mocks [InboxPageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockInboxPageCubit extends _i1.Mock implements _i11.InboxPageCubit {
  MockInboxPageCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.InboxPageState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeInboxPageState_2(this, Invocation.getter(#state)),
          )
          as _i4.InboxPageState);

  @override
  _i12.Stream<_i4.InboxPageState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i4.InboxPageState>.empty(),
          )
          as _i12.Stream<_i4.InboxPageState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false) as bool);

  @override
  _i12.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> sendMessage(
    String? conversationId,
    _i13.MessageModel? message,
    _i14.GlobalKey<_i14.AnimatedListState>? listKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [conversationId, message, listKey]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> markMessageAsRead(String? conversationId, int? messageIndex) =>
      (super.noSuchMethod(
            Invocation.method(#markMessageAsRead, [conversationId, messageIndex]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [conversationId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void emit(_i4.InboxPageState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]), returnValueForMissingStub: null);

  @override
  void onChange(_i15.Change<_i4.InboxPageState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]), returnValueForMissingStub: null);

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [MessagesPageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessagesPageCubit extends _i1.Mock implements _i16.MessagesPageCubit {
  MockMessagesPageCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get activeRequestId =>
      (super.noSuchMethod(Invocation.getter(#activeRequestId), returnValue: 0) as int);

  @override
  set activeRequestId(int? _activeRequestId) => super.noSuchMethod(
    Invocation.setter(#activeRequestId, _activeRequestId),
    returnValueForMissingStub: null,
  );

  @override
  _i5.MessagesPageState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMessagesPageState_3(this, Invocation.getter(#state)),
          )
          as _i5.MessagesPageState);

  @override
  _i12.Stream<_i5.MessagesPageState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i5.MessagesPageState>.empty(),
          )
          as _i12.Stream<_i5.MessagesPageState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false) as bool);

  @override
  void setCurrentConversationId(String? conversationId) => super.noSuchMethod(
    Invocation.method(#setCurrentConversationId, [conversationId]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> updateMessageText(String? newText) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessageText, [newText]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateGifsSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#updateGifsSearch, [query]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void updateSelectedGif(String? newGifUrl) => super.noSuchMethod(
    Invocation.method(#updateSelectedGif, [newGifUrl]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<_i17.AttachmentEntity?> getAttachmentFile() =>
      (super.noSuchMethod(
            Invocation.method(#getAttachmentFile, []),
            returnValue: _i12.Future<_i17.AttachmentEntity?>.value(),
          )
          as _i12.Future<_i17.AttachmentEntity?>);

  @override
  void emit(_i5.MessagesPageState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]), returnValueForMissingStub: null);

  @override
  void onChange(_i15.Change<_i5.MessagesPageState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]), returnValueForMissingStub: null);

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}
