// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/domain/usecases/owners/get_owner_by_id_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_futter_project/domain/entities/owner_entity.dart' as _i2;
import 'package:test_futter_project/domain/repositories/owner_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOwnerEntity_0 extends _i1.SmartFake implements _i2.OwnerEntity {
  _FakeOwnerEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OwnerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOwnerRepository extends _i1.Mock implements _i3.OwnerRepository {
  MockOwnerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.OwnerEntity>> fetchOwners() =>
      (super.noSuchMethod(
            Invocation.method(#fetchOwners, []),
            returnValue: _i4.Future<List<_i2.OwnerEntity>>.value(
              <_i2.OwnerEntity>[],
            ),
          )
          as _i4.Future<List<_i2.OwnerEntity>>);

  @override
  _i2.OwnerEntity getOwnerById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getOwnerById, [id]),
            returnValue: _FakeOwnerEntity_0(
              this,
              Invocation.method(#getOwnerById, [id]),
            ),
          )
          as _i2.OwnerEntity);
}
