// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/domain/repositories/car_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_flutter_project/domain/entities/car_entity.dart' as _i2;
import 'package:test_flutter_project/domain/repositories/car_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCarEntity_0 extends _i1.SmartFake implements _i2.CarEntity {
  _FakeCarEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarRepository extends _i1.Mock implements _i3.CarRepository {
  MockCarRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.CarEntity> getAllCars() => (super.noSuchMethod(
        Invocation.method(
          #getAllCars,
          [],
        ),
        returnValue: <_i2.CarEntity>[],
      ) as List<_i2.CarEntity>);

  @override
  void addCar(_i2.CarEntity? car) => super.noSuchMethod(
        Invocation.method(
          #addCar,
          [car],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> syncCars() => (super.noSuchMethod(
        Invocation.method(
          #syncCars,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void deleteAll() => super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteCarById(String? id) => super.noSuchMethod(
        Invocation.method(
          #deleteCarById,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.CarEntity getCarById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getCarById,
          [id],
        ),
        returnValue: _FakeCarEntity_0(
          this,
          Invocation.method(
            #getCarById,
            [id],
          ),
        ),
      ) as _i2.CarEntity);

  @override
  int getMaxCarId() => (super.noSuchMethod(
        Invocation.method(
          #getMaxCarId,
          [],
        ),
        returnValue: 0,
      ) as int);
}
