// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/domain/usecases/car_colors/get_car_colors_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:test_futter_project/domain/repositories/car_color_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CarColorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarColorRepository extends _i1.Mock
    implements _i2.CarColorRepository {
  MockCarColorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i3.Color> getColors() =>
      (super.noSuchMethod(
            Invocation.method(#getColors, []),
            returnValue: <String, _i3.Color>{},
          )
          as Map<String, _i3.Color>);

  @override
  _i3.Color? getColorByName(String? colorName) =>
      (super.noSuchMethod(Invocation.method(#getColorByName, [colorName]))
          as _i3.Color?);

  @override
  String getColorNameFromColor(_i3.Color? color) =>
      (super.noSuchMethod(
            Invocation.method(#getColorNameFromColor, [color]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getColorNameFromColor, [color]),
            ),
          )
          as String);
}
