// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/data/repositories/car_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cancellation_token/cancellation_token.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:realm/realm.dart' as _i2;
import 'package:realm_common/realm_common.dart' as _i6;
import 'package:realm_dart/src/configuration.dart' as _i3;
import 'package:realm_dart/src/realm_object.dart' as _i7;
import 'package:realm_dart/src/results.dart' as _i5;
import 'package:test_futter_project/data/dto/car_dto.dart' as _i12;
import 'package:test_futter_project/data/models/scheme.dart' as _i8;
import 'package:test_futter_project/domain/data_sources/car_api_service.dart' as _i11;
import 'package:test_futter_project/domain/entities/car_entity.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDynamicRealm_0 extends _i1.SmartFake implements _i2.DynamicRealm {
  _FakeDynamicRealm_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeConfiguration_1 extends _i1.SmartFake implements _i3.Configuration {
  _FakeConfiguration_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealmSchema_2 extends _i1.SmartFake implements _i3.RealmSchema {
  _FakeRealmSchema_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeTransaction_3 extends _i1.SmartFake implements _i2.Transaction {
  _FakeTransaction_3(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeFuture_4<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_4(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeRealmResults_5<T1 extends Object?> extends _i1.SmartFake
    implements _i5.RealmResults<T1> {
  _FakeRealmResults_5(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeRealm_6 extends _i1.SmartFake implements _i2.Realm {
  _FakeRealm_6(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeObjectId_7 extends _i1.SmartFake implements _i6.ObjectId {
  _FakeObjectId_7(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeSchemaObject_8 extends _i1.SmartFake implements _i3.SchemaObject {
  _FakeSchemaObject_8(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeDynamicRealmObject_9 extends _i1.SmartFake implements _i7.DynamicRealmObject {
  _FakeDynamicRealmObject_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCar_10 extends _i1.SmartFake implements _i8.Car {
  _FakeCar_10(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [Realm].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealm extends _i1.Mock implements _i2.Realm {
  MockRealm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DynamicRealm get dynamic =>
      (super.noSuchMethod(
            Invocation.getter(#dynamic),
            returnValue: _FakeDynamicRealm_0(this, Invocation.getter(#dynamic)),
          )
          as _i2.DynamicRealm);

  @override
  _i3.Configuration get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeConfiguration_1(this, Invocation.getter(#config)),
          )
          as _i3.Configuration);

  @override
  _i3.RealmSchema get schema =>
      (super.noSuchMethod(
            Invocation.getter(#schema),
            returnValue: _FakeRealmSchema_2(this, Invocation.getter(#schema)),
          )
          as _i3.RealmSchema);

  @override
  bool get isFrozen =>
      (super.noSuchMethod(Invocation.getter(#isFrozen), returnValue: false) as bool);

  @override
  bool get isInTransaction =>
      (super.noSuchMethod(Invocation.getter(#isInTransaction), returnValue: false) as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false) as bool);

  @override
  set schema(_i3.RealmSchema? _schema) =>
      super.noSuchMethod(Invocation.setter(#schema, _schema), returnValueForMissingStub: null);

  @override
  T add<T extends _i7.RealmObject>(T? object, {bool? update = false}) =>
      (super.noSuchMethod(
            Invocation.method(#add, [object], {#update: update}),
            returnValue: _i9.dummyValue<T>(
              this,
              Invocation.method(#add, [object], {#update: update}),
            ),
          )
          as T);

  @override
  void addAll<T extends _i7.RealmObject>(Iterable<T>? items, {bool? update = false}) =>
      super.noSuchMethod(
        Invocation.method(#addAll, [items], {#update: update}),
        returnValueForMissingStub: null,
      );

  @override
  void delete<T extends _i7.RealmObjectBase>(T? object) =>
      super.noSuchMethod(Invocation.method(#delete, [object]), returnValueForMissingStub: null);

  @override
  void deleteMany<T extends _i7.RealmObject>(Iterable<T>? items) =>
      super.noSuchMethod(Invocation.method(#deleteMany, [items]), returnValueForMissingStub: null);

  @override
  T write<T>(T Function()? writeCallback) =>
      (super.noSuchMethod(
            Invocation.method(#write, [writeCallback]),
            returnValue: _i9.dummyValue<T>(this, Invocation.method(#write, [writeCallback])),
          )
          as T);

  @override
  _i2.Transaction beginWrite() =>
      (super.noSuchMethod(
            Invocation.method(#beginWrite, []),
            returnValue: _FakeTransaction_3(this, Invocation.method(#beginWrite, [])),
          )
          as _i2.Transaction);

  @override
  _i4.Future<_i2.Transaction> beginWriteAsync([_i10.CancellationToken? cancellationToken]) =>
      (super.noSuchMethod(
            Invocation.method(#beginWriteAsync, [cancellationToken]),
            returnValue: _i4.Future<_i2.Transaction>.value(
              _FakeTransaction_3(this, Invocation.method(#beginWriteAsync, [cancellationToken])),
            ),
          )
          as _i4.Future<_i2.Transaction>);

  @override
  _i4.Future<T> writeAsync<T>(
    T Function()? writeCallback, [
    _i10.CancellationToken? cancellationToken,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#writeAsync, [writeCallback, cancellationToken]),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#writeAsync, [writeCallback, cancellationToken]),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_4<T>(
                  this,
                  Invocation.method(#writeAsync, [writeCallback, cancellationToken]),
                ),
          )
          as _i4.Future<T>);

  @override
  void close() =>
      super.noSuchMethod(Invocation.method(#close, []), returnValueForMissingStub: null);

  @override
  _i5.RealmResults<T> all<T extends _i7.RealmObject>() =>
      (super.noSuchMethod(
            Invocation.method(#all, []),
            returnValue: _FakeRealmResults_5<T>(this, Invocation.method(#all, [])),
          )
          as _i5.RealmResults<T>);

  @override
  _i5.RealmResults<T> query<T extends _i7.RealmObject>(
    String? query, [
    List<Object?>? args = const [],
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#query, [query, args]),
            returnValue: _FakeRealmResults_5<T>(this, Invocation.method(#query, [query, args])),
          )
          as _i5.RealmResults<T>);

  @override
  void deleteAll<T extends _i7.RealmObject>() =>
      super.noSuchMethod(Invocation.method(#deleteAll, []), returnValueForMissingStub: null);

  @override
  _i2.Realm freeze() =>
      (super.noSuchMethod(
            Invocation.method(#freeze, []),
            returnValue: _FakeRealm_6(this, Invocation.method(#freeze, [])),
          )
          as _i2.Realm);

  @override
  void writeCopy(_i3.Configuration? config) =>
      super.noSuchMethod(Invocation.method(#writeCopy, [config]), returnValueForMissingStub: null);

  @override
  bool refresh() =>
      (super.noSuchMethod(Invocation.method(#refresh, []), returnValue: false) as bool);

  @override
  _i4.Future<bool> refreshAsync() =>
      (super.noSuchMethod(
            Invocation.method(#refreshAsync, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void disableAutoRefreshForTesting() => super.noSuchMethod(
    Invocation.method(#disableAutoRefreshForTesting, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CarApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarApiService extends _i1.Mock implements _i11.CarApiService {
  MockCarApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i12.CarDto>> get carStream =>
      (super.noSuchMethod(
            Invocation.getter(#carStream),
            returnValue: _i4.Stream<List<_i12.CarDto>>.empty(),
          )
          as _i4.Stream<List<_i12.CarDto>>);

  @override
  _i4.Future<List<_i12.CarDto>> fetchCars() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCars, []),
            returnValue: _i4.Future<List<_i12.CarDto>>.value(<_i12.CarDto>[]),
          )
          as _i4.Future<List<_i12.CarDto>>);

  @override
  void dispose() =>
      super.noSuchMethod(Invocation.method(#dispose, []), returnValueForMissingStub: null);
}

/// A class which mocks [Car].
///
/// See the documentation for Mockito's code generation for more information.
class MockCar extends _i1.Mock implements _i8.Car {
  MockCar() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ObjectId get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _FakeObjectId_7(this, Invocation.getter(#id)),
          )
          as _i6.ObjectId);

  @override
  String get carId =>
      (super.noSuchMethod(
            Invocation.getter(#carId),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#carId)),
          )
          as String);

  @override
  String get manufacturer =>
      (super.noSuchMethod(
            Invocation.getter(#manufacturer),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#manufacturer)),
          )
          as String);

  @override
  int get price => (super.noSuchMethod(Invocation.getter(#price), returnValue: 0) as int);

  @override
  _i4.Stream<_i7.RealmObjectChanges<_i8.Car>> get changes =>
      (super.noSuchMethod(
            Invocation.getter(#changes),
            returnValue: _i4.Stream<_i7.RealmObjectChanges<_i8.Car>>.empty(),
          )
          as _i4.Stream<_i7.RealmObjectChanges<_i8.Car>>);

  @override
  _i3.SchemaObject get objectSchema =>
      (super.noSuchMethod(
            Invocation.getter(#objectSchema),
            returnValue: _FakeSchemaObject_8(this, Invocation.getter(#objectSchema)),
          )
          as _i3.SchemaObject);

  @override
  set id(_i6.ObjectId? value) =>
      super.noSuchMethod(Invocation.setter(#id, value), returnValueForMissingStub: null);

  @override
  set carId(String? value) =>
      super.noSuchMethod(Invocation.setter(#carId, value), returnValueForMissingStub: null);

  @override
  set manufacturer(String? value) =>
      super.noSuchMethod(Invocation.setter(#manufacturer, value), returnValueForMissingStub: null);

  @override
  set model(String? value) =>
      super.noSuchMethod(Invocation.setter(#model, value), returnValueForMissingStub: null);

  @override
  set year(String? value) =>
      super.noSuchMethod(Invocation.setter(#year, value), returnValueForMissingStub: null);

  @override
  set isChecked(bool? value) =>
      super.noSuchMethod(Invocation.setter(#isChecked, value), returnValueForMissingStub: null);

  @override
  set isHotProposition(bool? value) => super.noSuchMethod(
    Invocation.setter(#isHotProposition, value),
    returnValueForMissingStub: null,
  );

  @override
  set kilometers(int? value) =>
      super.noSuchMethod(Invocation.setter(#kilometers, value), returnValueForMissingStub: null);

  @override
  set distanceTo(int? value) =>
      super.noSuchMethod(Invocation.setter(#distanceTo, value), returnValueForMissingStub: null);

  @override
  set price(int? value) =>
      super.noSuchMethod(Invocation.setter(#price, value), returnValueForMissingStub: null);

  @override
  set owner(_i8.Person? value) =>
      super.noSuchMethod(Invocation.setter(#owner, value), returnValueForMissingStub: null);

  @override
  _i2.Realm get realm =>
      (super.noSuchMethod(
            Invocation.getter(#realm),
            returnValue: _FakeRealm_6(this, Invocation.getter(#realm)),
          )
          as _i2.Realm);

  @override
  bool get isManaged =>
      (super.noSuchMethod(Invocation.getter(#isManaged), returnValue: false) as bool);

  @override
  bool get isFrozen =>
      (super.noSuchMethod(Invocation.getter(#isFrozen), returnValue: false) as bool);

  @override
  _i7.DynamicRealmObject get dynamic =>
      (super.noSuchMethod(
            Invocation.getter(#dynamic),
            returnValue: _FakeDynamicRealmObject_9(this, Invocation.getter(#dynamic)),
          )
          as _i7.DynamicRealmObject);

  @override
  bool get isValid => (super.noSuchMethod(Invocation.getter(#isValid), returnValue: false) as bool);

  @override
  _i4.Stream<_i7.RealmObjectChanges<_i8.Car>> changesFor([List<String>? keyPaths]) =>
      (super.noSuchMethod(
            Invocation.method(#changesFor, [keyPaths]),
            returnValue: _i4.Stream<_i7.RealmObjectChanges<_i8.Car>>.empty(),
          )
          as _i4.Stream<_i7.RealmObjectChanges<_i8.Car>>);

  @override
  _i8.Car freeze() =>
      (super.noSuchMethod(
            Invocation.method(#freeze, []),
            returnValue: _FakeCar_10(this, Invocation.method(#freeze, [])),
          )
          as _i8.Car);

  @override
  _i5.RealmResults<T> getBacklinks<T>(String? propertyName) =>
      (super.noSuchMethod(
            Invocation.method(#getBacklinks, [propertyName]),
            returnValue: _FakeRealmResults_5<T>(
              this,
              Invocation.method(#getBacklinks, [propertyName]),
            ),
          )
          as _i5.RealmResults<T>);
}

/// A class which mocks [CarEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarEntity extends _i1.Mock implements _i13.CarEntity {
  MockCarEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get carId =>
      (super.noSuchMethod(
            Invocation.getter(#carId),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#carId)),
          )
          as String);

  @override
  String get model =>
      (super.noSuchMethod(
            Invocation.getter(#model),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#model)),
          )
          as String);

  @override
  String get manufacturer =>
      (super.noSuchMethod(
            Invocation.getter(#manufacturer),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#manufacturer)),
          )
          as String);

  @override
  bool get isVerified =>
      (super.noSuchMethod(Invocation.getter(#isVerified), returnValue: false) as bool);

  @override
  bool get isHotPromotion =>
      (super.noSuchMethod(Invocation.getter(#isHotPromotion), returnValue: false) as bool);

  @override
  set kilometers(int? _kilometers) => super.noSuchMethod(
    Invocation.setter(#kilometers, _kilometers),
    returnValueForMissingStub: null,
  );

  @override
  set distanceTo(int? _distanceTo) => super.noSuchMethod(
    Invocation.setter(#distanceTo, _distanceTo),
    returnValueForMissingStub: null,
  );

  @override
  set price(int? _price) =>
      super.noSuchMethod(Invocation.setter(#price, _price), returnValueForMissingStub: null);
}

/// A class which mocks [CarDto].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarDto extends _i1.Mock implements _i12.CarDto {
  MockCarDto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ObjectId get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _FakeObjectId_7(this, Invocation.getter(#id)),
          )
          as _i6.ObjectId);

  @override
  String get carId =>
      (super.noSuchMethod(
            Invocation.getter(#carId),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#carId)),
          )
          as String);

  @override
  String get model =>
      (super.noSuchMethod(
            Invocation.getter(#model),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#model)),
          )
          as String);

  @override
  String get manufacturer =>
      (super.noSuchMethod(
            Invocation.getter(#manufacturer),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#manufacturer)),
          )
          as String);

  @override
  bool get isVerified =>
      (super.noSuchMethod(Invocation.getter(#isVerified), returnValue: false) as bool);

  @override
  bool get isHotPromotion =>
      (super.noSuchMethod(Invocation.getter(#isHotPromotion), returnValue: false) as bool);

  @override
  set kilometers(int? _kilometers) => super.noSuchMethod(
    Invocation.setter(#kilometers, _kilometers),
    returnValueForMissingStub: null,
  );

  @override
  set distanceTo(int? _distanceTo) => super.noSuchMethod(
    Invocation.setter(#distanceTo, _distanceTo),
    returnValueForMissingStub: null,
  );

  @override
  set price(int? _price) =>
      super.noSuchMethod(Invocation.setter(#price, _price), returnValueForMissingStub: null);
}
