// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/domain/usecases/regions/fetch_regions_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_futter_project/domain/entities/region_entity.dart' as _i4;
import 'package:test_futter_project/domain/repositories/region_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RegionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegionRepository extends _i1.Mock implements _i2.RegionRepository {
  MockRegionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> loadRegions() => (super.noSuchMethod(
        Invocation.method(
          #loadRegions,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i4.RegionEntity? getRegionByCode(String? code) =>
      (super.noSuchMethod(Invocation.method(
        #getRegionByCode,
        [code],
      )) as _i4.RegionEntity?);

  @override
  List<_i4.RegionEntity> getAllRegions() => (super.noSuchMethod(
        Invocation.method(
          #getAllRegions,
          [],
        ),
        returnValue: <_i4.RegionEntity>[],
      ) as List<_i4.RegionEntity>);
}
