// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/presentation/widgets/dialogs/color_picker_dialog/color_picker_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:test_flutter_project/domain/usecases/car_colors/get_car_color_by_name_use_case.dart'
    as _i2;
import 'package:test_flutter_project/domain/usecases/car_colors/get_car_color_name_from_color_use_case.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetCarColorByNameUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCarColorByNameUseCase extends _i1.Mock
    implements _i2.GetCarColorByNameUseCase {
  MockGetCarColorByNameUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Color? call(String? colorName) => (super.noSuchMethod(Invocation.method(
        #call,
        [colorName],
      )) as _i3.Color?);
}

/// A class which mocks [GetCarColorNameFromColorUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCarColorNameFromColorUseCase extends _i1.Mock
    implements _i4.GetCarColorNameFromColorUseCase {
  MockGetCarColorNameFromColorUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String call(_i3.Color? color) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [color],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #call,
            [color],
          ),
        ),
      ) as String);
}
