// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/presentation/pages/account/sub_pages/location_settings/location_settings_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:test_flutter_project/domain/entities/region_entity.dart' as _i3;
import 'package:test_flutter_project/domain/models/region_ui_model.dart' as _i5;
import 'package:test_flutter_project/domain/usecases/regions/get_all_region_models_use_case.dart'
    as _i4;
import 'package:test_flutter_project/domain/usecases/regions/get_region_by_code_use_case.dart'
    as _i2;
import 'package:test_flutter_project/presentation/features/location_settings/location_settings_page_cubit.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetRegionByCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRegionByCodeUseCase extends _i1.Mock
    implements _i2.GetRegionByCodeUseCase {
  @override
  _i3.RegionEntity? call(String? code) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [code],
        ),
        returnValueForMissingStub: null,
      ) as _i3.RegionEntity?);
}

/// A class which mocks [GetAllRegionModelsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllRegionModelsUseCase extends _i1.Mock
    implements _i4.GetAllRegionModelsUseCase {
  @override
  List<_i5.RegionUiModel> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: <_i5.RegionUiModel>[],
        returnValueForMissingStub: <_i5.RegionUiModel>[],
      ) as List<_i5.RegionUiModel>);
}

/// A class which mocks [LocationSettingsPageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationSettingsPageCubit extends _i1.Mock
    implements _i6.LocationSettingsPageCubit {
  @override
  _i7.Stream<Object?> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i7.Stream<Object?>.empty(),
        returnValueForMissingStub: _i7.Stream<Object?>.empty(),
      ) as _i7.Stream<Object?>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.RegionEntity? getRegionByCode(String? code) => (super.noSuchMethod(
        Invocation.method(
          #getRegionByCode,
          [code],
        ),
        returnValueForMissingStub: null,
      ) as _i3.RegionEntity?);

  @override
  List<_i5.RegionUiModel> getAvailableCountries() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableCountries,
          [],
        ),
        returnValue: <_i5.RegionUiModel>[],
        returnValueForMissingStub: <_i5.RegionUiModel>[],
      ) as List<_i5.RegionUiModel>);

  @override
  _i7.Future<void> openUrl(String? url) => (super.noSuchMethod(
        Invocation.method(
          #openUrl,
          [url],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void emit(Object? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i8.Change<Object?>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
