// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/presentation/pages/account/sub_pages/location_settings/location_settings_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_bloc/flutter_bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:test_flutter_project/presentation/features/location_settings/location_settings_page_cubit.dart'
    as _i3;
import 'package:test_flutter_project/presentation/features/location_settings/location_settings_page_state.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocationSettingsPageState_0 extends _i1.SmartFake
    implements _i2.LocationSettingsPageState {
  _FakeLocationSettingsPageState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocationSettingsPageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationSettingsPageCubit extends _i1.Mock
    implements _i3.LocationSettingsPageCubit {
  @override
  _i2.LocationSettingsPageState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeLocationSettingsPageState_0(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeLocationSettingsPageState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.LocationSettingsPageState);

  @override
  _i4.Stream<_i2.LocationSettingsPageState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.LocationSettingsPageState>.empty(),
        returnValueForMissingStub:
            _i4.Stream<_i2.LocationSettingsPageState>.empty(),
      ) as _i4.Stream<_i2.LocationSettingsPageState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void loadCurrentRegionByCode(String? code) => super.noSuchMethod(
        Invocation.method(
          #loadCurrentRegionByCode,
          [code],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateAvailableCountries() => super.noSuchMethod(
        Invocation.method(
          #updateAvailableCountries,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> openUrl(String? url) => (super.noSuchMethod(
        Invocation.method(
          #openUrl,
          [url],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void emit(_i2.LocationSettingsPageState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i5.Change<_i2.LocationSettingsPageState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
