// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/domain/usecases/inbox/fetch_conversations_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_futter_project/domain/models/conversation_model.dart'
    as _i2;
import 'package:test_futter_project/domain/repositories/inbox_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConversationModel_0 extends _i1.SmartFake
    implements _i2.ConversationModel {
  _FakeConversationModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InboxRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInboxRepository extends _i1.Mock implements _i3.InboxRepository {
  MockInboxRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ConversationModel>> fetchConversations() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchConversations,
          [],
        ),
        returnValue: _i4.Future<List<_i2.ConversationModel>>.value(
            <_i2.ConversationModel>[]),
      ) as _i4.Future<List<_i2.ConversationModel>>);

  @override
  _i2.ConversationModel getConversationById(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversationById,
          [conversationId],
        ),
        returnValue: _FakeConversationModel_0(
          this,
          Invocation.method(
            #getConversationById,
            [conversationId],
          ),
        ),
      ) as _i2.ConversationModel);

  @override
  _i2.ConversationModel getConversationByOwnerId(String? ownerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversationByOwnerId,
          [ownerId],
        ),
        returnValue: _FakeConversationModel_0(
          this,
          Invocation.method(
            #getConversationByOwnerId,
            [ownerId],
          ),
        ),
      ) as _i2.ConversationModel);

  @override
  _i4.Future<void> saveConversations(
          List<_i2.ConversationModel>? conversations) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConversations,
          [conversations],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
