// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/presentation/pages/search/widgets/model_filter_drawer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:test_futter_project/common/enums/car_type.dart' as _i6;
import 'package:test_futter_project/common/enums/drawer_type.dart' as _i7;
import 'package:test_futter_project/domain/entities/car_entity.dart' as _i5;
import 'package:test_futter_project/presentation/bloc/search/search_page_cubit.dart'
    as _i3;
import 'package:test_futter_project/presentation/bloc/search/search_page_state.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSearchPageState_0 extends _i1.SmartFake
    implements _i2.SearchPageState {
  _FakeSearchPageState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchPageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchPageCubit extends _i1.Mock implements _i3.SearchPageCubit {
  MockSearchPageCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SearchPageState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSearchPageState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.SearchPageState);

  @override
  _i4.Stream<_i2.SearchPageState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.SearchPageState>.empty(),
          )
          as _i4.Stream<_i2.SearchPageState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void init() => super.noSuchMethod(
    Invocation.method(#init, []),
    returnValueForMissingStub: null,
  );

  @override
  void loadData() => super.noSuchMethod(
    Invocation.method(#loadData, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i5.CarEntity> applyAllFilters(List<_i5.CarEntity>? cars) =>
      (super.noSuchMethod(
            Invocation.method(#applyAllFilters, [cars]),
            returnValue: <_i5.CarEntity>[],
          )
          as List<_i5.CarEntity>);

  @override
  void updateTypeSelection(_i6.CarType? newType) => super.noSuchMethod(
    Invocation.method(#updateTypeSelection, [newType]),
    returnValueForMissingStub: null,
  );

  @override
  void updateModelListFromEntities(
    List<_i5.CarEntity>? cars,
    _i6.CarType? type,
  ) => super.noSuchMethod(
    Invocation.method(#updateModelListFromEntities, [cars, type]),
    returnValueForMissingStub: null,
  );

  @override
  void updateModelSelection(List<String>? newList) => super.noSuchMethod(
    Invocation.method(#updateModelSelection, [newList]),
    returnValueForMissingStub: null,
  );

  @override
  void addCarModelToSelection(String? model) => super.noSuchMethod(
    Invocation.method(#addCarModelToSelection, [model]),
    returnValueForMissingStub: null,
  );

  @override
  void removeCarModelFromSelection(String? model) => super.noSuchMethod(
    Invocation.method(#removeCarModelFromSelection, [model]),
    returnValueForMissingStub: null,
  );

  @override
  void addBodyTypeToSelection(String? bodyType) => super.noSuchMethod(
    Invocation.method(#addBodyTypeToSelection, [bodyType]),
    returnValueForMissingStub: null,
  );

  @override
  void removeBodyTypeFromSelection(String? bodyType) => super.noSuchMethod(
    Invocation.method(#removeBodyTypeFromSelection, [bodyType]),
    returnValueForMissingStub: null,
  );

  @override
  void addFuelTypeToSelection(String? fuelType) => super.noSuchMethod(
    Invocation.method(#addFuelTypeToSelection, [fuelType]),
    returnValueForMissingStub: null,
  );

  @override
  void removeFuelTypeFromSelection(String? fuelType) => super.noSuchMethod(
    Invocation.method(#removeFuelTypeFromSelection, [fuelType]),
    returnValueForMissingStub: null,
  );

  @override
  void addTransmissionTypeToSelection(String? transmissionType) =>
      super.noSuchMethod(
        Invocation.method(#addTransmissionTypeToSelection, [transmissionType]),
        returnValueForMissingStub: null,
      );

  @override
  void removeTransmissionTypeFromSelection(String? transmissionType) =>
      super.noSuchMethod(
        Invocation.method(#removeTransmissionTypeFromSelection, [
          transmissionType,
        ]),
        returnValueForMissingStub: null,
      );

  @override
  void updateSelectedMinYear(String? newValue) => super.noSuchMethod(
    Invocation.method(#updateSelectedMinYear, [newValue]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSelectedMaxYear(String? newValue) => super.noSuchMethod(
    Invocation.method(#updateSelectedMaxYear, [newValue]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSelectedMinPrice(String? newValue) => super.noSuchMethod(
    Invocation.method(#updateSelectedMinPrice, [newValue]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSelectedMaxPrice(String? newValue) => super.noSuchMethod(
    Invocation.method(#updateSelectedMaxPrice, [newValue]),
    returnValueForMissingStub: null,
  );

  @override
  void openDrawer(_i7.SearchDrawerType? type) => super.noSuchMethod(
    Invocation.method(#openDrawer, [type]),
    returnValueForMissingStub: null,
  );

  @override
  bool validateYears(String? minYearString, String? maxYearString) =>
      (super.noSuchMethod(
            Invocation.method(#validateYears, [minYearString, maxYearString]),
            returnValue: false,
          )
          as bool);

  @override
  bool validatePrices(String? minPriceString, String? maxPriceString) =>
      (super.noSuchMethod(
            Invocation.method(#validatePrices, [
              minPriceString,
              maxPriceString,
            ]),
            returnValue: false,
          )
          as bool);

  @override
  int getSelectedFilterCount() =>
      (super.noSuchMethod(
            Invocation.method(#getSelectedFilterCount, []),
            returnValue: 0,
          )
          as int);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void emit(_i2.SearchPageState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i8.Change<_i2.SearchPageState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
