// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/presentation/pages/search/widgets/model_filter_drawer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:test_futter_project/common/enums/car_type.dart' as _i5;
import 'package:test_futter_project/common/enums/drawer_type.dart' as _i7;
import 'package:test_futter_project/domain/entities/car_entity.dart' as _i6;
import 'package:test_futter_project/presentation/bloc/search/search_page_cubit.dart'
    as _i3;
import 'package:test_futter_project/presentation/bloc/search/search_page_state.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSearchPageState_0 extends _i1.SmartFake
    implements _i2.SearchPageState {
  _FakeSearchPageState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchPageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchPageCubit extends _i1.Mock implements _i3.SearchPageCubit {
  MockSearchPageCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SearchPageState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSearchPageState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.SearchPageState);

  @override
  _i4.Stream<_i2.SearchPageState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.SearchPageState>.empty(),
          )
          as _i4.Stream<_i2.SearchPageState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void loadData() => super.noSuchMethod(
    Invocation.method(#loadData, []),
    returnValueForMissingStub: null,
  );

  @override
  void updateTypeSelection(_i5.CarType? newType) => super.noSuchMethod(
    Invocation.method(#updateTypeSelection, [newType]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i6.CarEntity> filterCarsByType(List<_i6.CarEntity>? list) =>
      (super.noSuchMethod(
            Invocation.method(#filterCarsByType, [list]),
            returnValue: <_i6.CarEntity>[],
          )
          as List<_i6.CarEntity>);

  @override
  List<_i6.CarEntity> filterCarsByModel(List<_i6.CarEntity>? list) =>
      (super.noSuchMethod(
            Invocation.method(#filterCarsByModel, [list]),
            returnValue: <_i6.CarEntity>[],
          )
          as List<_i6.CarEntity>);

  @override
  void updateModelListFromEntities(
    List<_i6.CarEntity>? cars,
    _i5.CarType? type,
  ) => super.noSuchMethod(
    Invocation.method(#updateModelListFromEntities, [cars, type]),
    returnValueForMissingStub: null,
  );

  @override
  void updateModelSelection(List<String>? newList) => super.noSuchMethod(
    Invocation.method(#updateModelSelection, [newList]),
    returnValueForMissingStub: null,
  );

  @override
  void addCarModelToSelection(String? model) => super.noSuchMethod(
    Invocation.method(#addCarModelToSelection, [model]),
    returnValueForMissingStub: null,
  );

  @override
  void removeCarModelFromSelection(String? model) => super.noSuchMethod(
    Invocation.method(#removeCarModelFromSelection, [model]),
    returnValueForMissingStub: null,
  );

  @override
  void openDrawer(_i7.SearchDrawerType? type) => super.noSuchMethod(
    Invocation.method(#openDrawer, [type]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void emit(_i2.SearchPageState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i8.Change<_i2.SearchPageState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
