// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/utils/app_router_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:test_futter_project/common/enums/car_type.dart' as _i14;
import 'package:test_futter_project/common/enums/drawer_type.dart' as _i15;
import 'package:test_futter_project/domain/entities/car_entity.dart' as _i11;
import 'package:test_futter_project/domain/entities/user_entity.dart' as _i4;
import 'package:test_futter_project/presentation/bloc/home/explore_page/explore_page_cubit.dart'
    as _i10;
import 'package:test_futter_project/presentation/bloc/home/explore_page/explore_page_state.dart'
    as _i3;
import 'package:test_futter_project/presentation/bloc/home/home_bottom_bar/home_bottom_bar_cubit.dart'
    as _i7;
import 'package:test_futter_project/presentation/bloc/home/home_bottom_bar/home_bottom_bar_state.dart'
    as _i2;
import 'package:test_futter_project/presentation/bloc/search/search_page_cubit.dart'
    as _i13;
import 'package:test_futter_project/presentation/bloc/search/search_page_state.dart'
    as _i6;
import 'package:test_futter_project/presentation/bloc/user/user_data_cubit.dart'
    as _i12;
import 'package:test_futter_project/presentation/bloc/user/user_data_state.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeBottomBarState_0 extends _i1.SmartFake
    implements _i2.HomeBottomBarState {
  _FakeHomeBottomBarState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExplorePageState_1 extends _i1.SmartFake
    implements _i3.ExplorePageState {
  _FakeExplorePageState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserEntity_2 extends _i1.SmartFake implements _i4.UserEntity {
  _FakeUserEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserDataState_3 extends _i1.SmartFake implements _i5.UserDataState {
  _FakeUserDataState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchPageState_4 extends _i1.SmartFake
    implements _i6.SearchPageState {
  _FakeSearchPageState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeBottomBarCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeBottomBarCubit extends _i1.Mock
    implements _i7.HomeBottomBarCubit {
  MockHomeBottomBarCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeBottomBarState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeHomeBottomBarState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.HomeBottomBarState);

  @override
  _i8.Stream<_i2.HomeBottomBarState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i2.HomeBottomBarState>.empty(),
          )
          as _i8.Stream<_i2.HomeBottomBarState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void updateSelectedIndex(int? newIndex) => super.noSuchMethod(
    Invocation.method(#updateSelectedIndex, [newIndex]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.HomeBottomBarState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i9.Change<_i2.HomeBottomBarState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [ExplorePageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockExplorePageCubit extends _i1.Mock implements _i10.ExplorePageCubit {
  MockExplorePageCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ExplorePageState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeExplorePageState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.ExplorePageState);

  @override
  _i8.Stream<_i3.ExplorePageState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i3.ExplorePageState>.empty(),
          )
          as _i8.Stream<_i3.ExplorePageState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i8.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void updateCars(List<_i11.CarEntity>? newValue) => super.noSuchMethod(
    Invocation.method(#updateCars, [newValue]),
    returnValueForMissingStub: null,
  );

  @override
  void removeCarAt(int? index) => super.noSuchMethod(
    Invocation.method(#removeCarAt, [index]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void emit(_i3.ExplorePageState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i9.Change<_i3.ExplorePageState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserDataCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataCubit extends _i1.Mock implements _i12.UserDataCubit {
  MockUserDataCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.UserEntity get user =>
      (super.noSuchMethod(
            Invocation.getter(#user),
            returnValue: _FakeUserEntity_2(this, Invocation.getter(#user)),
          )
          as _i4.UserEntity);

  @override
  set user(_i4.UserEntity? _user) => super.noSuchMethod(
    Invocation.setter(#user, _user),
    returnValueForMissingStub: null,
  );

  @override
  _i5.UserDataState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeUserDataState_3(this, Invocation.getter(#state)),
          )
          as _i5.UserDataState);

  @override
  _i8.Stream<_i5.UserDataState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i5.UserDataState>.empty(),
          )
          as _i8.Stream<_i5.UserDataState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void init() => super.noSuchMethod(
    Invocation.method(#init, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> requestLocationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestLocationPermission, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void updateLocationPermissionStatus(bool? newStatus) => super.noSuchMethod(
    Invocation.method(#updateLocationPermissionStatus, [newStatus]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.UserDataState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i9.Change<_i5.UserDataState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [SearchPageCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchPageCubit extends _i1.Mock implements _i13.SearchPageCubit {
  MockSearchPageCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.SearchPageState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSearchPageState_4(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i6.SearchPageState);

  @override
  _i8.Stream<_i6.SearchPageState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i6.SearchPageState>.empty(),
          )
          as _i8.Stream<_i6.SearchPageState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void init() => super.noSuchMethod(
    Invocation.method(#init, []),
    returnValueForMissingStub: null,
  );

  @override
  void loadData() => super.noSuchMethod(
    Invocation.method(#loadData, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i11.CarEntity> applyAllFilters(List<_i11.CarEntity>? cars) =>
      (super.noSuchMethod(
            Invocation.method(#applyAllFilters, [cars]),
            returnValue: <_i11.CarEntity>[],
          )
          as List<_i11.CarEntity>);

  @override
  void updateTypeSelection(_i14.CarType? newType) => super.noSuchMethod(
    Invocation.method(#updateTypeSelection, [newType]),
    returnValueForMissingStub: null,
  );

  @override
  void updateModelListFromEntities(
    List<_i11.CarEntity>? cars,
    _i14.CarType? type,
  ) => super.noSuchMethod(
    Invocation.method(#updateModelListFromEntities, [cars, type]),
    returnValueForMissingStub: null,
  );

  @override
  void updateModelSelection(List<String>? newList) => super.noSuchMethod(
    Invocation.method(#updateModelSelection, [newList]),
    returnValueForMissingStub: null,
  );

  @override
  void addCarModelToSelection(String? model) => super.noSuchMethod(
    Invocation.method(#addCarModelToSelection, [model]),
    returnValueForMissingStub: null,
  );

  @override
  void removeCarModelFromSelection(String? model) => super.noSuchMethod(
    Invocation.method(#removeCarModelFromSelection, [model]),
    returnValueForMissingStub: null,
  );

  @override
  void addBodyTypeToSelection(String? bodyType) => super.noSuchMethod(
    Invocation.method(#addBodyTypeToSelection, [bodyType]),
    returnValueForMissingStub: null,
  );

  @override
  void removeBodyTypeFromSelection(String? bodyType) => super.noSuchMethod(
    Invocation.method(#removeBodyTypeFromSelection, [bodyType]),
    returnValueForMissingStub: null,
  );

  @override
  void addFuelTypeToSelection(String? fuelType) => super.noSuchMethod(
    Invocation.method(#addFuelTypeToSelection, [fuelType]),
    returnValueForMissingStub: null,
  );

  @override
  void removeFuelTypeFromSelection(String? fuelType) => super.noSuchMethod(
    Invocation.method(#removeFuelTypeFromSelection, [fuelType]),
    returnValueForMissingStub: null,
  );

  @override
  void addTransmissionTypeToSelection(String? transmissionType) =>
      super.noSuchMethod(
        Invocation.method(#addTransmissionTypeToSelection, [transmissionType]),
        returnValueForMissingStub: null,
      );

  @override
  void removeTransmissionTypeFromSelection(String? transmissionType) =>
      super.noSuchMethod(
        Invocation.method(#removeTransmissionTypeFromSelection, [
          transmissionType,
        ]),
        returnValueForMissingStub: null,
      );

  @override
  void updateSelectedMinYear(String? newValue) => super.noSuchMethod(
    Invocation.method(#updateSelectedMinYear, [newValue]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSelectedMaxYear(String? newValue) => super.noSuchMethod(
    Invocation.method(#updateSelectedMaxYear, [newValue]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSelectedMinPrice(String? newValue) => super.noSuchMethod(
    Invocation.method(#updateSelectedMinPrice, [newValue]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSelectedMaxPrice(String? newValue) => super.noSuchMethod(
    Invocation.method(#updateSelectedMaxPrice, [newValue]),
    returnValueForMissingStub: null,
  );

  @override
  void openDrawer(_i15.SearchDrawerType? type) => super.noSuchMethod(
    Invocation.method(#openDrawer, [type]),
    returnValueForMissingStub: null,
  );

  @override
  bool validateYears(String? minYearString, String? maxYearString) =>
      (super.noSuchMethod(
            Invocation.method(#validateYears, [minYearString, maxYearString]),
            returnValue: false,
          )
          as bool);

  @override
  bool validatePrices(String? minPriceString, String? maxPriceString) =>
      (super.noSuchMethod(
            Invocation.method(#validatePrices, [
              minPriceString,
              maxPriceString,
            ]),
            returnValue: false,
          )
          as bool);

  @override
  int getSelectedFilterCount() =>
      (super.noSuchMethod(
            Invocation.method(#getSelectedFilterCount, []),
            returnValue: 0,
          )
          as int);

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void emit(_i6.SearchPageState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i9.Change<_i6.SearchPageState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
