// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/common/fakes/common_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:flutter_bloc/flutter_bloc.dart' as _i19;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:test_flutter_project/domain/data_sources/local/app_local_storage.dart'
    as _i11;
import 'package:test_flutter_project/domain/data_sources/remote/owners_remote_data_source.dart'
    as _i8;
import 'package:test_flutter_project/domain/data_sources/remote/users_remote_data_source.dart'
    as _i10;
import 'package:test_flutter_project/domain/entities/car_entity.dart' as _i12;
import 'package:test_flutter_project/domain/entities/owner_entity.dart' as _i2;
import 'package:test_flutter_project/domain/entities/user_entity.dart' as _i3;
import 'package:test_flutter_project/domain/models/auth_result.dart' as _i16;
import 'package:test_flutter_project/domain/repositories/auth_repository.dart'
    as _i15;
import 'package:test_flutter_project/domain/repositories/car_repository.dart'
    as _i13;
import 'package:test_flutter_project/domain/repositories/user_repository.dart'
    as _i14;
import 'package:test_flutter_project/domain/services/logging_service.dart'
    as _i6;
import 'package:test_flutter_project/domain/services/time_service.dart' as _i7;
import 'package:test_flutter_project/presentation/features/l10n/app_localisations_cubit.dart'
    as _i20;
import 'package:test_flutter_project/presentation/features/l10n/app_localisations_state.dart'
    as _i5;
import 'package:test_flutter_project/presentation/features/user/user_data_cubit.dart'
    as _i18;
import 'package:test_flutter_project/presentation/features/user/user_data_state.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOwnerEntity_1 extends _i1.SmartFake implements _i2.OwnerEntity {
  _FakeOwnerEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserEntity_2 extends _i1.SmartFake implements _i3.UserEntity {
  _FakeUserEntity_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserDataState_3 extends _i1.SmartFake implements _i4.UserDataState {
  _FakeUserDataState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppLocalisationsState_4 extends _i1.SmartFake
    implements _i5.AppLocalisationsState {
  _FakeAppLocalisationsState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoggingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggingService extends _i1.Mock implements _i6.LoggingService {
  @override
  void verbose(String? message) => super.noSuchMethod(
        Invocation.method(
          #verbose,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void debug(String? message) => super.noSuchMethod(
        Invocation.method(
          #debug,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message) => super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message) => super.noSuchMethod(
        Invocation.method(
          #warning,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimeService extends _i1.Mock implements _i7.TimeService {
  @override
  DateTime now() => (super.noSuchMethod(
        Invocation.method(
          #now,
          [],
        ),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.method(
            #now,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDateTime_0(
          this,
          Invocation.method(
            #now,
            [],
          ),
        ),
      ) as DateTime);
}

/// A class which mocks [OwnersRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOwnersRemoteDataSource extends _i1.Mock
    implements _i8.OwnersRemoteDataSource {
  @override
  _i9.Future<List<_i2.OwnerEntity>> fetchOwners() => (super.noSuchMethod(
        Invocation.method(
          #fetchOwners,
          [],
        ),
        returnValue:
            _i9.Future<List<_i2.OwnerEntity>>.value(<_i2.OwnerEntity>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i2.OwnerEntity>>.value(<_i2.OwnerEntity>[]),
      ) as _i9.Future<List<_i2.OwnerEntity>>);

  @override
  _i2.OwnerEntity getOwnerById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getOwnerById,
          [id],
        ),
        returnValue: _FakeOwnerEntity_1(
          this,
          Invocation.method(
            #getOwnerById,
            [id],
          ),
        ),
        returnValueForMissingStub: _FakeOwnerEntity_1(
          this,
          Invocation.method(
            #getOwnerById,
            [id],
          ),
        ),
      ) as _i2.OwnerEntity);
}

/// A class which mocks [UsersRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsersRemoteDataSource extends _i1.Mock
    implements _i10.UsersRemoteDataSource {
  @override
  List<_i3.UserEntity> get users => (super.noSuchMethod(
        Invocation.getter(#users),
        returnValue: <_i3.UserEntity>[],
        returnValueForMissingStub: <_i3.UserEntity>[],
      ) as List<_i3.UserEntity>);

  @override
  set users(List<_i3.UserEntity>? _users) => super.noSuchMethod(
        Invocation.setter(
          #users,
          _users,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> saveSeedUsers(List<_i3.UserEntity>? users) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSeedUsers,
          [users],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i3.UserEntity>> loadSeedUsers() => (super.noSuchMethod(
        Invocation.method(
          #loadSeedUsers,
          [],
        ),
        returnValue: _i9.Future<List<_i3.UserEntity>>.value(<_i3.UserEntity>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i3.UserEntity>>.value(<_i3.UserEntity>[]),
      ) as _i9.Future<List<_i3.UserEntity>>);

  @override
  _i3.UserEntity? getUserByEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #getUserByEmail,
          [email],
        ),
        returnValueForMissingStub: null,
      ) as _i3.UserEntity?);

  @override
  int getMaxUserId() => (super.noSuchMethod(
        Invocation.method(
          #getMaxUserId,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.UserEntity? getUserById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i3.UserEntity?);
}

/// A class which mocks [AppLocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalStorage extends _i1.Mock implements _i11.AppLocalStorage {
  @override
  List<_i12.CarEntity> getAllCars() => (super.noSuchMethod(
        Invocation.method(
          #getAllCars,
          [],
        ),
        returnValue: <_i12.CarEntity>[],
        returnValueForMissingStub: <_i12.CarEntity>[],
      ) as List<_i12.CarEntity>);

  @override
  void addCar(_i12.CarEntity? car) => super.noSuchMethod(
        Invocation.method(
          #addCar,
          [car],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateCar(_i12.CarEntity? car) => super.noSuchMethod(
        Invocation.method(
          #updateCar,
          [car],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Stream<dynamic> watchCars() => (super.noSuchMethod(
        Invocation.method(
          #watchCars,
          [],
        ),
        returnValue: _i9.Stream<dynamic>.empty(),
        returnValueForMissingStub: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  void deleteAllCars() => super.noSuchMethod(
        Invocation.method(
          #deleteAllCars,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteCarById(String? id) => super.noSuchMethod(
        Invocation.method(
          #deleteCarById,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.CarEntity? getCarById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getCarById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i12.CarEntity?);

  @override
  int getMaxCarId() => (super.noSuchMethod(
        Invocation.method(
          #getMaxCarId,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.UserEntity initUser() => (super.noSuchMethod(
        Invocation.method(
          #initUser,
          [],
        ),
        returnValue: _FakeUserEntity_2(
          this,
          Invocation.method(
            #initUser,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeUserEntity_2(
          this,
          Invocation.method(
            #initUser,
            [],
          ),
        ),
      ) as _i3.UserEntity);

  @override
  void updateUser(_i3.UserEntity? user) => super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearUser() => super.noSuchMethod(
        Invocation.method(
          #clearUser,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarRepository extends _i1.Mock implements _i13.CarRepository {
  @override
  List<_i12.CarEntity> getAllCars() => (super.noSuchMethod(
        Invocation.method(
          #getAllCars,
          [],
        ),
        returnValue: <_i12.CarEntity>[],
        returnValueForMissingStub: <_i12.CarEntity>[],
      ) as List<_i12.CarEntity>);

  @override
  void addCar(_i12.CarEntity? car) => super.noSuchMethod(
        Invocation.method(
          #addCar,
          [car],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> syncCars() => (super.noSuchMethod(
        Invocation.method(
          #syncCars,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Stream<List<_i12.CarEntity>> watchCars() => (super.noSuchMethod(
        Invocation.method(
          #watchCars,
          [],
        ),
        returnValue: _i9.Stream<List<_i12.CarEntity>>.empty(),
        returnValueForMissingStub: _i9.Stream<List<_i12.CarEntity>>.empty(),
      ) as _i9.Stream<List<_i12.CarEntity>>);

  @override
  void deleteAll() => super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteCarById(String? id) => super.noSuchMethod(
        Invocation.method(
          #deleteCarById,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.CarEntity? getCarById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getCarById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i12.CarEntity?);

  @override
  int getMaxCarId() => (super.noSuchMethod(
        Invocation.method(
          #getMaxCarId,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i14.UserRepository {
  @override
  int getMaxUserId() => (super.noSuchMethod(
        Invocation.method(
          #getMaxUserId,
          [],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.UserEntity? getUserByEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #getUserByEmail,
          [email],
        ),
        returnValueForMissingStub: null,
      ) as _i3.UserEntity?);

  @override
  _i3.UserEntity? getUserById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i3.UserEntity?);

  @override
  _i9.Future<List<_i3.UserEntity>> loadSeedUsers() => (super.noSuchMethod(
        Invocation.method(
          #loadSeedUsers,
          [],
        ),
        returnValue: _i9.Future<List<_i3.UserEntity>>.value(<_i3.UserEntity>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i3.UserEntity>>.value(<_i3.UserEntity>[]),
      ) as _i9.Future<List<_i3.UserEntity>>);

  @override
  _i9.Future<void> saveSeedUsers(List<_i3.UserEntity>? users) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSeedUsers,
          [users],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i3.UserEntity initUser() => (super.noSuchMethod(
        Invocation.method(
          #initUser,
          [],
        ),
        returnValue: _FakeUserEntity_2(
          this,
          Invocation.method(
            #initUser,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeUserEntity_2(
          this,
          Invocation.method(
            #initUser,
            [],
          ),
        ),
      ) as _i3.UserEntity);

  @override
  void updateUser(_i3.UserEntity? user) => super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i15.AuthRepository {
  @override
  _i9.Future<_i16.AuthResult> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue:
            _i9.Future<_i16.AuthResult>.value(_i17.dummyValue<_i16.AuthResult>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i16.AuthResult>.value(_i17.dummyValue<_i16.AuthResult>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i9.Future<_i16.AuthResult>);

  @override
  _i9.Future<_i16.AuthResult> register({
    required String? email,
    required String? password,
    required String? firstName,
    required String? lastName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #email: email,
            #password: password,
            #firstName: firstName,
            #lastName: lastName,
          },
        ),
        returnValue:
            _i9.Future<_i16.AuthResult>.value(_i17.dummyValue<_i16.AuthResult>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i16.AuthResult>.value(_i17.dummyValue<_i16.AuthResult>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
            },
          ),
        )),
      ) as _i9.Future<_i16.AuthResult>);

  @override
  _i9.Future<void> logOut() => (super.noSuchMethod(
        Invocation.method(
          #logOut,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteAccount(String? email) => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [email],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateUser(_i3.UserEntity? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<bool> isUserLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isUserLoggedIn,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);
}

/// A class which mocks [UserDataCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataCubit extends _i1.Mock implements _i18.UserDataCubit {
  @override
  _i4.UserDataState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeUserDataState_3(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeUserDataState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.UserDataState);

  @override
  _i9.Stream<_i4.UserDataState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i9.Stream<_i4.UserDataState>.empty(),
        returnValueForMissingStub: _i9.Stream<_i4.UserDataState>.empty(),
      ) as _i9.Stream<_i4.UserDataState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i9.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<bool> isLocationPermissionGranted() => (super.noSuchMethod(
        Invocation.method(
          #isLocationPermissionGranted,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  void setFirstName(String? firstName) => super.noSuchMethod(
        Invocation.method(
          #setFirstName,
          [firstName],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastName(String? lastName) => super.noSuchMethod(
        Invocation.method(
          #setLastName,
          [lastName],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setEmail(String? email) => super.noSuchMethod(
        Invocation.method(
          #setEmail,
          [email],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPassword(String? password) => super.noSuchMethod(
        Invocation.method(
          #setPassword,
          [password],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLastSeenCar(String? carId) => super.noSuchMethod(
        Invocation.method(
          #setLastSeenCar,
          [carId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void checkLastSeenCarExpiration({required int? days}) => super.noSuchMethod(
        Invocation.method(
          #checkLastSeenCarExpiration,
          [],
          {#days: days},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> requestLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestLocationPermission,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<bool> openLocationSettings() => (super.noSuchMethod(
        Invocation.method(
          #openLocationSettings,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  void updateLocationPermissionStatus(bool? newStatus) => super.noSuchMethod(
        Invocation.method(
          #updateLocationPermissionStatus,
          [newStatus],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> updateAvatarImage() => (super.noSuchMethod(
        Invocation.method(
          #updateAvatarImage,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void addCarIdToFavorites(String? carId) => super.noSuchMethod(
        Invocation.method(
          #addCarIdToFavorites,
          [carId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeCarIdFromFavorites(String? carId) => super.noSuchMethod(
        Invocation.method(
          #removeCarIdFromFavorites,
          [carId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addCarIdToCreated(String? carId) => super.noSuchMethod(
        Invocation.method(
          #addCarIdToCreated,
          [carId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeCarIdFromCreated(String? carId) => super.noSuchMethod(
        Invocation.method(
          #removeCarIdFromCreated,
          [carId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addCarToRecentlyViewed(String? carId) => super.noSuchMethod(
        Invocation.method(
          #addCarToRecentlyViewed,
          [carId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearFavorites() => super.noSuchMethod(
        Invocation.method(
          #clearFavorites,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearRecentItems() => super.noSuchMethod(
        Invocation.method(
          #clearRecentItems,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearMyItems() => super.noSuchMethod(
        Invocation.method(
          #clearMyItems,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAllData() => super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateRegion(String? region) => super.noSuchMethod(
        Invocation.method(
          #updateRegion,
          [region],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> authUser(String? email) => (super.noSuchMethod(
        Invocation.method(
          #authUser,
          [email],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void logOutUser() => super.noSuchMethod(
        Invocation.method(
          #logOutUser,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateUser({
    required _i3.UserEntity? user,
    bool? updateCloud = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [],
          {
            #user: user,
            #updateCloud: updateCloud,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.UserDataState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i19.Change<_i4.UserDataState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [AppLocalisationsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalisationsCubit extends _i1.Mock
    implements _i20.AppLocalisationsCubit {
  @override
  _i5.AppLocalisationsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAppLocalisationsState_4(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeAppLocalisationsState_4(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.AppLocalisationsState);

  @override
  _i9.Stream<_i5.AppLocalisationsState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i9.Stream<_i5.AppLocalisationsState>.empty(),
        returnValueForMissingStub:
            _i9.Stream<_i5.AppLocalisationsState>.empty(),
      ) as _i9.Stream<_i5.AppLocalisationsState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i9.Future<void> initLocalisation(String? locale) => (super.noSuchMethod(
        Invocation.method(
          #initLocalisation,
          [locale],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void load(Map<String, String>? newLocalisations) => super.noSuchMethod(
        Invocation.method(
          #load,
          [newLocalisations],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getLocalisationByKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getLocalisationByKey,
          [key],
        ),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.method(
            #getLocalisationByKey,
            [key],
          ),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.method(
            #getLocalisationByKey,
            [key],
          ),
        ),
      ) as String);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i5.AppLocalisationsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i19.Change<_i5.AppLocalisationsState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}
