// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/presentation/pages/home/new_item_page/new_item_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:test_futter_project/domain/entities/car_entity.dart' as _i3;
import 'package:test_futter_project/domain/usecases/database/add_car_use_case.dart'
    as _i2;
import 'package:test_futter_project/domain/usecases/database/get_all_cars_use_case.dart'
    as _i4;
import 'package:test_futter_project/domain/usecases/database/get_current_max_car_id_use_case.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AddCarUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddCarUseCase extends _i1.Mock implements _i2.AddCarUseCase {
  MockAddCarUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call(_i3.CarEntity? params) => super.noSuchMethod(
    Invocation.method(#call, [params]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GetAllCarsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCarsUseCase extends _i1.Mock implements _i4.GetAllCarsUseCase {
  MockGetAllCarsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.CarEntity> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: <_i3.CarEntity>[],
          )
          as List<_i3.CarEntity>);
}

/// A class which mocks [GetCurrentMaxCarIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentMaxCarIdUseCase extends _i1.Mock
    implements _i5.GetCurrentMaxCarIdUseCase {
  MockGetCurrentMaxCarIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int call() =>
      (super.noSuchMethod(Invocation.method(#call, []), returnValue: 0) as int);
}
