// Mocks generated by Mockito 5.4.6 from annotations
// in test_flutter_project/test/domain/usecases/users/get_max_user_id_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_flutter_project/domain/entities/user_entity.dart' as _i3;
import 'package:test_flutter_project/domain/repositories/user_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int getMaxUserId() =>
      (super.noSuchMethod(Invocation.method(#getMaxUserId, []), returnValue: 0) as int);

  @override
  _i3.UserEntity? getUserByEmail(String? email) =>
      (super.noSuchMethod(Invocation.method(#getUserByEmail, [email])) as _i3.UserEntity?);

  @override
  _i3.UserEntity? getUserById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getUserById, [id])) as _i3.UserEntity?);

  @override
  _i4.Future<List<_i3.UserEntity>> loadMockUsers() =>
      (super.noSuchMethod(
            Invocation.method(#loadMockUsers, []),
            returnValue: _i4.Future<List<_i3.UserEntity>>.value(<_i3.UserEntity>[]),
          )
          as _i4.Future<List<_i3.UserEntity>>);

  @override
  _i4.Future<void> saveMockUsers(List<_i3.UserEntity>? users) =>
      (super.noSuchMethod(
            Invocation.method(#saveMockUsers, [users]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
