// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/presentation/bloc/authentication/authentication_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_futter_project/domain/models/auth_result.dart' as _i3;
import 'package:test_futter_project/domain/models/login_model.dart' as _i7;
import 'package:test_futter_project/domain/models/register_model.dart' as _i9;
import 'package:test_futter_project/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:test_futter_project/domain/usecases/authentication/login_use_case.dart'
    as _i6;
import 'package:test_futter_project/domain/usecases/authentication/logout_use_case.dart'
    as _i4;
import 'package:test_futter_project/domain/usecases/authentication/register_use_case.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_1 extends _i1.SmartFake implements _i3.AuthResult {
  _FakeAuthResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i4.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i6.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.AuthResult> call(_i7.LoginModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#call, [model]),
            returnValue: _i5.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(this, Invocation.method(#call, [model])),
            ),
          )
          as _i5.Future<_i3.AuthResult>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i8.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.AuthResult> call(_i9.RegisterModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#call, [model]),
            returnValue: _i5.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(this, Invocation.method(#call, [model])),
            ),
          )
          as _i5.Future<_i3.AuthResult>);
}
