// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/presentation/bloc/inbox/inbox_page_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_futter_project/domain/models/conversation_model.dart'
    as _i4;
import 'package:test_futter_project/domain/usecases/inbox/fetch_conversations_use_case.dart'
    as _i2;
import 'package:test_futter_project/domain/usecases/inbox/save_conversations_use_case.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FetchConversationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchConversationsUseCase extends _i1.Mock
    implements _i2.FetchConversationsUseCase {
  MockFetchConversationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ConversationModel>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<List<_i4.ConversationModel>>.value(
            <_i4.ConversationModel>[]),
      ) as _i3.Future<List<_i4.ConversationModel>>);
}

/// A class which mocks [SaveConversationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveConversationsUseCase extends _i1.Mock
    implements _i5.SaveConversationsUseCase {
  MockSaveConversationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(List<_i4.ConversationModel>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
