// Mocks generated by Mockito 5.4.6 from annotations
// in test_futter_project/test/domain/repositories/base_local_storage_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:realm/realm.dart' as _i6;
import 'package:test_futter_project/domain/entities/car_entity.dart' as _i4;
import 'package:test_futter_project/domain/entities/user_entity.dart' as _i2;
import 'package:test_futter_project/domain/repositories/base_local_storage.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BaseLocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseLocalStorage extends _i1.Mock implements _i3.BaseLocalStorage {
  MockBaseLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.CarEntity> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: <_i4.CarEntity>[],
          )
          as List<_i4.CarEntity>);

  @override
  void add(dynamic T) => super.noSuchMethod(
    Invocation.method(#add, [T]),
    returnValueForMissingStub: null,
  );

  @override
  void update(dynamic T) => super.noSuchMethod(
    Invocation.method(#update, [T]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<dynamic> watch<T>() =>
      (super.noSuchMethod(
            Invocation.method(#watch, []),
            returnValue: _i5.Stream<dynamic>.empty(),
          )
          as _i5.Stream<dynamic>);

  @override
  void deleteAll() => super.noSuchMethod(
    Invocation.method(#deleteAll, []),
    returnValueForMissingStub: null,
  );

  @override
  void deleteById(_i6.ObjectId? id) => super.noSuchMethod(
    Invocation.method(#deleteById, [id]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.UserEntity initUser() =>
      (super.noSuchMethod(
            Invocation.method(#initUser, []),
            returnValue: _FakeUserEntity_0(
              this,
              Invocation.method(#initUser, []),
            ),
          )
          as _i2.UserEntity);
}
